export const CHECKLISTS = [
  {
    slug: 'epub-formatting-checklist',
    metaTitle: '22-Point EPUB Formatting Checklist Before Upload — BookKraft AI',
    metaDescription: 'Run through this 22-point EPUB formatting checklist before uploading to KDP, Apple Books, or Draft2Digital. Covers manuscript cleanup, structure, metadata, cover, and validation.',
    title: '22-Point EPUB Formatting Checklist Before Upload',
    intro: '<p>A formatted EPUB that passes this checklist will pass technical validation on KDP, Apple Books, and Draft2Digital. The items are grouped by category — work through each section before uploading, even for re-uploads after minor changes. A file regenerated after a small edit can introduce new structural issues the original didn\'t have.</p>',
    sections: [
      {
        heading: 'Manuscript & Content',
        items: [
          'Double spaces removed — find-and-replace "  " (two spaces) with " " (one space) throughout',
          'Straight quotes converted to curly quotes, or left straight if your house style requires it — no mix of both',
          'Encoding artifacts removed: no replacement characters (□), stray byte-order marks, or Windows-1252 characters in a UTF-8 file',
          'Empty paragraph tags deleted from HTML chapter files — use CSS margin for spacing, not blank <p> tags',
          'Zero-width space characters (U+200B) searched and removed from all chapter files',
          'Front matter complete: title page, copyright page, dedication (if applicable)',
          'Back matter complete: author bio, Also By page, acknowledgements (if applicable), mailing list CTA',
        ],
      },
      {
        heading: 'Structure & Navigation',
        items: [
          'Table of contents present, correctly structured, and links resolve to correct chapter anchors',
          'NCX file (toc.ncx) present in OEBPS folder and referenced in OPF manifest with correct media-type',
          'nav.xhtml present for EPUB 3 files with a valid <nav epub:type="toc"> element',
          'OPF spine lists all chapters in the correct reading order with no duplicate idrefs',
          'All files listed in OPF manifest actually exist inside the EPUB ZIP package',
          'No files exist in the EPUB package that are not declared in the OPF manifest',
        ],
      },
      {
        heading: 'Metadata',
        items: [
          'dc:title populated and non-empty in content.opf',
          'dc:creator populated with author name in content.opf',
          'dc:language set to a valid BCP 47 code (e.g., "en" or "en-US") in content.opf',
          'dc:identifier present — either a valid ISBN-13 or a unique UUID',
        ],
      },
      {
        heading: 'Cover & Images',
        items: [
          'Cover image declared in OPF manifest with properties="cover-image" and correct media-type',
          'Cover image minimum 1600px on the short side (KDP recommendation; Apple Books requires 1400px minimum)',
          'All embedded images saved as JPG, PNG, or GIF — no EMF, WMF, BMP, or TIFF inside the EPUB',
          'Image MIME types correctly declared in OPF manifest entries',
        ],
      },
      {
        heading: 'Validation',
        items: [
          'EPUB validated with EPUBCheck (current version) — zero Critical and Error-level issues resolved',
          'File opened in at least one e-reader app (Kindle Previewer or Calibre) to confirm visual rendering before upload',
          'Total EPUB file size within platform limits (KDP: 650MB; Apple Books: 2GB; D2D: 300MB recommended)',
        ],
      },
    ],
    faq: [
      {
        q: 'Does passing this checklist guarantee my book won\'t be rejected?',
        a: 'The structural and validation checks here prevent the vast majority of technical rejections. Content policy rejections — flagged cover images, prohibited content categories, or duplicate content flags — are outside the scope of this checklist and depend on each platform\'s content guidelines.',
      },
      {
        q: 'How often should I run through this checklist?',
        a: 'For every upload or re-upload, including minor updates. Even fixing a typo can introduce encoding issues or break the manifest if the EPUB is regenerated by a conversion tool. The checklist takes under 10 minutes once the workflow is established.',
      },
      {
        q: 'My EPUB passes EPUBCheck but still gets rejected — what\'s left to check?',
        a: 'EPUBCheck validates structural compliance. Platform-specific rejection causes that EPUBCheck doesn\'t catch include: cover image color profiles (Apple Books rejects CMYK), ISBN format in content.opf (Apple Books requires scheme="ISBN"), and duplicate content flags (KDP compares against existing ASINs). See the platform-specific checklists for Apple Books and KDP for those details.',
      },
    ],
    relatedTool: 'epub-validator',
    related: [
      { type: 'platform-rejection', slug: 'amazon-kdp', label: 'Why Amazon KDP rejects ebooks' },
      { type: 'platform-rejection', slug: 'apple-books', label: 'Why Apple Books rejects ebooks' },
      { type: 'epub-error', slug: 'missing-ncx-navigation', label: 'Missing NCX navigation table' },
      { type: 'epub-error', slug: 'ghost-spacing-epub', label: 'Ghost spacing in e-reader previews' },
    ],
  },
  {
    slug: 'kdp-pre-launch-checklist',
    metaTitle: '20-Point KDP Pre-Launch Checklist — BookKraft AI',
    metaDescription: 'KDP-specific pre-launch checklist covering Kindle TOC format, keyword and category setup, KDP Select decision, pricing, and Kindle Previewer testing — beyond generic EPUB validation.',
    title: '20-Point KDP Pre-Launch Checklist',
    intro: '<p>This checklist picks up where EPUB validation leaves off. It assumes your file is already structurally valid and covers the Amazon-specific layer: Kindle navigation requirements, KDP metadata, content review, and publishing setup decisions that don\'t apply to other platforms. Complete the EPUB formatting checklist first if you haven\'t already, then work through these KDP-specific steps before hitting Publish.</p>',
    sections: [
      {
        heading: 'File Preparation',
        items: [
          'Kindle TOC structure verified: navPoints in toc.ncx reference valid chapter files and match the inline TOC',
          'Spine order confirmed as correct reading order — no missing or duplicate idrefs in content.opf',
          'Cover image is JPG or TIFF, minimum 1000px on the short side, with a 2:3 aspect ratio (1600×2560px recommended)',
          'EPUB file size under 650MB compressed — strip unused fonts, resize oversized images if needed',
        ],
      },
      {
        heading: 'KDP Metadata',
        items: [
          'Book title in KDP dashboard matches the title on the cover image exactly — KDP flags discrepancies during review',
          'Author name matches your existing Amazon Author Page (if one exists) to consolidate your author profile',
          '7 keyword slots populated with long-tail phrases (3-5 words each), not single keywords',
          '2 BISAC category paths selected — choose the most specific subcategory available, not top-level categories',
          'Book description formatted in KDP\'s HTML editor: bold opening sentence, short paragraphs, no raw HTML tags visible to readers',
        ],
      },
      {
        heading: 'Content Review',
        items: [
          'AI-generated content declaration completed in KDP\'s content guidelines section if any AI tools were used in writing or editing',
          'No URLs linking to Amazon competitor storefronts embedded in the book content',
          'Content is sufficiently differentiated from any existing ASIN on Amazon, including your own prior editions',
          'Back matter "Also by" links point to your Amazon Author Page or Amazon ASINs, not external sites',
        ],
      },
      {
        heading: 'Publishing Setup',
        items: [
          'KDP Select enrollment decision made — KDP Select requires 90-day exclusivity to Amazon, blocking D2D and direct distribution',
          'Pricing reviewed using KDP\'s Pricing Support tool to confirm royalty rate (70% royalty requires $2.99–$9.99 list price in most markets)',
          'Territory rights set correctly: Worldwide if you own global rights, specific territories if rights are limited',
          'Print edition (paperback/hardcover) set up separately if applicable — print interiors require a PDF, not an EPUB',
        ],
      },
      {
        heading: 'Pre-Publish Preview',
        items: [
          'Book previewed in Kindle Previewer desktop app after uploading — confirms the Kindle conversion, not just the raw EPUB',
          'Table of contents accessible from the Kindle menu navigation (Go To > Table of Contents), not just the inline page',
          'Enhanced Typesetting compatibility confirmed: justified text, drop caps, and image positioning render correctly on newer Kindle devices',
        ],
      },
    ],
    faq: [
      {
        q: 'Do I need to run this checklist every time I update my book?',
        a: 'For full re-uploads (new EPUB or cover file), yes — work through the File Preparation and Pre-Publish Preview sections. For metadata-only updates (price change, description edit, keyword swap), skip File Preparation and focus on the KDP Metadata and Publishing Setup sections.',
      },
      {
        q: 'What\'s the difference between this checklist and the general EPUB formatting checklist?',
        a: 'The EPUB formatting checklist covers structural validity that applies to all platforms — EPUBCheck compliance, manifest completeness, cover dimensions. This KDP checklist covers the Amazon-specific layer: Kindle TOC format differences, KDP keyword and category mechanics, KDP Select enrollment, and Kindle Previewer testing. These steps don\'t apply to Apple Books or Draft2Digital uploads.',
      },
      {
        q: 'Will my book be rejected if I don\'t declare AI-generated content?',
        a: "KDP's AI-generated content policy requires disclosure when AI tools were used to create text, images, or translations. KDP reserves the right to remove undisclosed AI content, and repeated violations can result in account suspension. If any AI tools were involved in writing or editing — including AI writing assistants, not just full-generation tools — complete the disclosure.",
      },
    ],
    relatedTool: 'epub-validator',
    related: [
      { type: 'platform-rejection', slug: 'amazon-kdp', label: 'Why Amazon KDP rejects ebooks' },
      { type: 'epub-error', slug: 'missing-ncx-navigation', label: 'Missing NCX navigation table' },
      { type: 'epub-error', slug: 'broken-spine-order', label: 'Broken spine order errors' },
      { type: 'epub-error', slug: 'cover-image-not-declared', label: 'Cover image not declared in OPF manifest' },
      { type: 'alternative', slug: 'scrivener-alternative', label: 'Scrivener alternative for ebook production' },
    ],
  },
  {
    slug: 'apple-books-submission-checklist',
    metaTitle: '21-Point Apple Books Submission Checklist — BookKraft AI',
    metaDescription: 'Apple Books has the strictest EPUB validation of any major platform. This 21-point checklist covers EPUBCheck compliance, ISBN requirements, cover color profiles, nav.xhtml structure, and rights declarations.',
    title: '21-Point Apple Books Submission Checklist',
    intro: '<p>Use this list as a pre-submission gate, not a post-rejection diagnostic. Work through each category before opening Apple Books Connect — most items in the File Validation and Navigation sections belong in your file-preparation workflow, not on the upload screen. The cover color mode check and the ISBN format in content.opf are the two Apple-specific requirements most commonly overlooked by authors publishing to KDP first and Apple Books second.</p>',
    sections: [
      {
        heading: 'File Validation',
        items: [
          'Run EPUBCheck 5.x on the final packaged EPUB and confirm the report shows zero Critical or Error-level issues — Apple\'s ingestion pipeline rejects any file with outstanding errors, no appeal process',
          'Open each XHTML chapter file in a markup validator — Apple checks HTML compliance inside chapter documents, a step beyond standard OPF and manifest checking',
          'Search across all chapter files for duplicate id attributes and remove every duplicate before zipping the EPUB',
          'Scan all EPUB 3 content files for EPUB 2 vestiges such as opf:role attributes — mixed-version markup triggers Apple\'s schema validator',
          'Audit the CSS file for deprecated or non-standard properties — Apple\'s reading engine promotes certain parse warnings to blocking errors during ingestion',
        ],
      },
      {
        heading: 'Required Metadata',
        items: [
          'Add ISBN-13 to content.opf: <dc:identifier opf:scheme="ISBN">978...</dc:identifier> — paid submissions without a properly formatted ISBN are blocked at the intake stage',
          'Verify dc:title, dc:creator, and dc:language are populated in content.opf — empty fields are rejected even if the same data is entered in Apple Books Connect',
          'Write a minimum 50-word description in Apple Books Connect — below this the editorial review queue may flag for insufficient metadata',
          'Enter a publisher name in Apple Books Connect (required field in the Connect interface, independent of content.opf)',
          'Select subject/BISAC codes in Apple Books Connect — category assignment is mandatory before submission unlocks',
        ],
      },
      {
        heading: 'Cover File',
        items: [
          'Export cover image at minimum 1400×2100 pixels — Apple\'s intake system measures pixel dimensions and rejects any cover below this floor',
          'Save as JPG or PNG in RGB color mode — CMYK output from print-production workflows is one of the most frequent Apple-specific rejection causes',
          'Embed an sRGB color profile in the cover file — tools such as Affinity Publisher default to document profiles other than sRGB on export',
          'Confirm body images are JPG, PNG, or GIF and that each has a matching MIME type declaration in the OPF manifest',
        ],
      },
      {
        heading: 'Navigation & Structure',
        items: [
          'Confirm nav.xhtml exists and its <nav epub:type="toc"> element contains a properly nested ordered list of chapter links',
          'Check that nav.xhtml carries properties="nav" in the OPF manifest entry',
          'Include toc.ncx for backward compatibility with older Apple hardware running legacy iBooks builds',
          'Verify the OPF spine sequence: every idref points to a declared manifest item and the order matches intended reading order',
        ],
      },
      {
        heading: 'Rights & Distribution',
        items: [
          'Set territory rights in Apple Books Connect to match your actual rights scope — selecting Worldwide when rights are restricted triggers a rights conflict review',
          'Review the book against Apple\'s content guidelines before submitting — flags for explicit content or prohibited categories arrive as post-submission rejections, not upload errors',
          'If using an aggregator (Draft2Digital, Smashwords), verify the aggregator is not also configured to deliver to Apple Books — duplicate listings are removed, and the direct submission takes precedence',
        ],
      },
    ],
    faq: [
      {
        q: 'My EPUB passed EPUBCheck but Apple Books still rejected it — why?',
        a: "Apple validates against some Apple-specific schema rules beyond standard EPUBCheck, particularly for nav.xhtml structure, ISBN format, and cover image color profiles. The rejection email includes specific error codes — check those first. The three most common Apple-specific failures that pass EPUBCheck are: CMYK cover images, missing or incorrectly formatted ISBN-13, and nav.xhtml missing the epub:type attribute.",
      },
      {
        q: 'Is an ISBN required to publish on Apple Books?',
        a: "For paid books distributed directly through Apple Books Connect, yes — a valid ISBN-13 is required as the dc:identifier. For free books, Apple may accept a UUID-based identifier. If you don't have an ISBN, aggregators like Draft2Digital provide free ISBNs — though using a D2D ISBN means D2D manages the book's Apple Books listing, not you directly.",
      },
      {
        q: 'Does this checklist apply if I\'m distributing to Apple Books through Draft2Digital?',
        a: "Most items still apply — D2D runs its own pre-conversion validation before sending to Apple, and a file that fails Apple's requirements will be rejected regardless of how it was submitted. The Rights & Territory section is the main difference: D2D handles the Apple Books Connect account, so you set territory rights in D2D's interface rather than directly in Apple Books Connect.",
      },
    ],
    relatedTool: 'epub-validator',
    related: [
      { type: 'platform-rejection', slug: 'apple-books', label: 'Why Apple Books rejects ebooks' },
      { type: 'epub-error', slug: 'duplicate-id-epub', label: 'Duplicate ID attribute errors' },
      { type: 'epub-error', slug: 'missing-ncx-navigation', label: 'Missing NCX navigation table' },
      { type: 'epub-error', slug: 'malformed-xhtml-unclosed-tag', label: 'Malformed XHTML — unclosed tags in chapter files' },
      { type: 'alternative', slug: 'jutoh-alternative', label: 'Jutoh alternative for EPUB formatting' },
    ],
  },
];

export function getChecklistBySlug(slug) {
  return CHECKLISTS.find((c) => c.slug === slug) ?? null;
}
