export const CHECKLISTS = [
  {
    slug: 'epub-formatting-checklist',
    metaTitle: '22-Point EPUB Formatting Checklist Before Upload — BookKraft AI',
    metaDescription: 'Run through this 22-point EPUB formatting checklist before uploading to KDP, Apple Books, or Draft2Digital. Covers manuscript cleanup, structure, metadata, cover, and validation.',
    title: '22-Point EPUB Formatting Checklist Before Upload',
    intro: '<p>A formatted EPUB that passes this checklist meets the technical requirements for KDP, Apple Books, and Draft2Digital. The items are grouped by category — work through each section before uploading, even for re-uploads after minor changes. A file regenerated after a small edit can introduce new structural issues the original didn\'t have.</p>',
    sections: [
      {
        heading: 'Manuscript & Content',
        items: [
          'Double spaces removed — find-and-replace "  " (two spaces) with " " (one space) throughout',
          'Straight quotes converted to curly quotes, or left straight if your house style requires it — no mix of both',
          'Encoding artifacts removed: no replacement characters (□), stray byte-order marks, or Windows-1252 characters in a UTF-8 file',
          'Empty paragraph tags deleted from HTML chapter files — use CSS margin for spacing, not blank <p> tags',
          'Zero-width space characters (U+200B) searched and removed from all chapter files',
          'Front matter complete: title page, copyright page, dedication (if applicable)',
          'Back matter complete: author bio, Also By page, acknowledgements (if applicable), mailing list CTA',
        ],
      },
      {
        heading: 'Structure & Navigation',
        items: [
          'Table of contents present, correctly structured, and links resolve to correct chapter anchors',
          'NCX file (toc.ncx) present in OEBPS folder and referenced in OPF manifest with correct media-type',
          'nav.xhtml present for EPUB 3 files with a valid <nav epub:type="toc"> element',
          'OPF spine lists all chapters in the correct reading order with no duplicate idrefs',
          'All files listed in OPF manifest actually exist inside the EPUB ZIP package',
          'No files exist in the EPUB package that are not declared in the OPF manifest',
        ],
      },
      {
        heading: 'Metadata',
        items: [
          'dc:title populated and non-empty in content.opf',
          'dc:creator populated with author name in content.opf',
          'dc:language set to a valid BCP 47 code (e.g., "en" or "en-US") in content.opf',
          'dc:identifier present — either a valid ISBN-13 or a unique UUID',
        ],
      },
      {
        heading: 'Cover & Images',
        items: [
          'Cover image declared in OPF manifest with properties="cover-image" and correct media-type',
          'Cover image minimum 1600px on the short side (KDP recommendation; Apple Books requires 1400px minimum)',
          'All embedded images saved as JPG, PNG, or GIF — no EMF, WMF, BMP, or TIFF inside the EPUB',
          'Image MIME types correctly declared in OPF manifest entries',
        ],
      },
      {
        heading: 'Validation',
        items: [
          'EPUB validated with EPUBCheck (current version) — zero Critical and Error-level issues resolved',
          'File opened in at least one e-reader app (Kindle Previewer or Calibre) to confirm visual rendering before upload',
          'Total EPUB file size within platform limits (KDP: 650MB; Apple Books: 2GB; D2D: 300MB recommended)',
        ],
      },
    ],
    faq: [
      {
        q: 'Does passing this checklist guarantee my book won\'t be rejected?',
        a: 'The structural and validation checks here prevent the vast majority of technical rejections. Content policy rejections — flagged cover images, prohibited content categories, or duplicate content flags — are outside the scope of this checklist and depend on each platform\'s content guidelines.',
      },
      {
        q: 'How often should I run through this checklist?',
        a: 'For every upload or re-upload, including minor updates. Even fixing a typo can introduce encoding issues or break the manifest if the EPUB is regenerated by a conversion tool. The checklist takes under 10 minutes once the workflow is established.',
      },
      {
        q: 'My EPUB passes EPUBCheck but still gets rejected — what\'s left to check?',
        a: 'EPUBCheck validates structural compliance. Platform-specific requirements that EPUBCheck doesn\'t check include: cover image color mode (Apple\'s Asset Guide says the cover art must use RGB color mode), ISBN format in content.opf (Apple Books requires scheme="ISBN"), and duplicate content flags (KDP compares against existing ASINs). See the platform-specific checklists for Apple Books and KDP for those details.',
      },
    ],
    relatedTool: 'epub-validator',
    related: [
      { type: 'platform-rejection', slug: 'amazon-kdp', label: 'Why Amazon KDP rejects ebooks' },
      { type: 'platform-rejection', slug: 'apple-books', label: 'Why Apple Books rejects ebooks' },
      { type: 'platform-rejection', slug: 'ingram-spark', label: 'Why IngramSpark rejects books' },
      { type: 'epub-error', slug: 'missing-ncx-navigation', label: 'Missing NCX navigation table' },
      { type: 'epub-error', slug: 'ghost-spacing-epub', label: 'Ghost spacing in e-reader previews' },
      { type: 'mistake', slug: 'epub-formatting-mistakes', label: '10 EPUB formatting mistakes that cause rejection' },
    ],
  },
  {
    slug: 'kdp-pre-launch-checklist',
    metaTitle: 'KDP Preflight Checklist: Check Your Book Before Upload | BookKraft AI',
    metaDescription: "Check your book before uploading to KDP: manuscript, EPUB, cover, metadata, keywords, categories and pricing — each step based on KDP's help pages, with free tools.",
    title: 'KDP Preflight Checklist: What to Check Before You Upload',
    pdfTitle: 'KDP Ebook Preflight Checklist',
    dateModified: '2026-10-08',
    optin: true,
    intro: "<p>Work through these checks before you upload a Kindle eBook to KDP. Each section links to the KDP help pages it is based on and to a free BookKraft tool that can help. Items that KDP's help pages don't cover are our advice. For EPUB structure in more depth, see the <a href=\"/checklist/epub-formatting-checklist\">EPUB formatting checklist</a>. First book on KDP? Read <a href=\"/blog/what-is-amazon-kdp-guide-for-new-authors\">what Amazon KDP is and how it works</a> before you start.</p>",
    sections: [
      {
        heading: 'Manuscript',
        items: [
          'Your file is in a format KDP accepts for eBooks: Word (DOC/DOCX), KPF or EPUB, or HTML, RTF or TXT (PDF is supported only for some languages)',
          'Tracked changes accepted and comments removed, so they can\'t end up in the book',
          'Any password protection removed from the file before you upload',
          'Double spaces, empty paragraphs and a mix of straight and curly quotes cleaned up',
          'Chapter titles use the same heading style throughout, so a table of contents can be built from them',
        ],
        tools: [{ slug: 'word-cleanup' }, { slug: 'manuscript-mode' }],
        sources: [
          { label: 'KDP: eBook manuscript formats', url: 'https://kdp.amazon.com/en_US/help/topic/G200634390' },
        ],
      },
      {
        heading: 'EPUB file',
        items: [
          'File is under 650 MB — KDP says larger files will not convert',
          'EPUB structure checked: mimetype, container, OPF package, spine and manifest',
          'Table of contents present and working (a nav document in EPUB 3)',
          'Every image and font the book uses is included in the file',
          'File checked in Kindle Previewer, which KDP recommends before you upload an EPUB',
        ],
        tools: [{ slug: 'epub-validator' }],
        sources: [
          { label: 'KDP: manuscript file size', url: 'https://kdp.amazon.com/en_US/help/topic/G200735140' },
          { label: 'KDP: eBook manuscript formats', url: 'https://kdp.amazon.com/en_US/help/topic/G200634390' },
          { label: 'W3C: EPUBCheck', url: 'https://www.w3.org/publishing/epubcheck/' },
        ],
      },
      {
        heading: 'Cover',
        items: [
          'Cover is a JPEG or TIFF file under 50 MB, in RGB color',
          'Cover is at least 1,000 × 625 pixels (height × width); KDP\'s ideal size is 2,560 × 1,600, a 1.6:1 ratio',
          'Title, subtitle, author name and series on the cover match what you enter in KDP',
          'Print edition: the paperback cover is a separate PDF with front, spine and back',
        ],
        tools: [{ slug: 'cover-checker' }],
        guides: [{ href: '/cover-requirements/amazon-kdp-ebook', label: 'KDP ebook cover requirements' }],
        sources: [
          { label: 'KDP: eBook cover requirements', url: 'https://kdp.amazon.com/en_US/help/topic/G200645690' },
          { label: 'KDP: metadata guidelines', url: 'https://kdp.amazon.com/en_US/help/topic/G201097560' },
          { label: 'KDP: paperback cover', url: 'https://kdp.amazon.com/en_US/help/topic/G201953020' },
        ],
      },
      {
        heading: 'Metadata',
        items: [
          'Title, subtitle, author and series in KDP match your cover',
          'Book description is 4,000 characters or fewer — KDP counts HTML tags too',
          'Language set to the language the book is written in',
          'ISBN decided: optional for Kindle eBooks; each print format needs its own',
          'AI-generated text, images or translations disclosed when you publish; AI-assisted editing doesn\'t need to be disclosed',
        ],
        tools: [{ slug: 'metadata-builder' }],
        sources: [
          { label: 'KDP: metadata guidelines', url: 'https://kdp.amazon.com/en_US/help/topic/G201097560' },
          { label: 'KDP: book description', url: 'https://kdp.amazon.com/en_US/help/topic/G201189630' },
          { label: 'KDP: ISBNs', url: 'https://kdp.amazon.com/en_US/help/topic/G201834170' },
          { label: 'KDP: content guidelines (AI content)', url: 'https://kdp.amazon.com/en_US/help/topic/G200672390' },
        ],
      },
      {
        heading: 'Keywords and categories',
        items: [
          'Up to 7 keywords or short phrases, using specific words in a logical order',
          'No terms KDP asks you to avoid: words already in your title, contributor names or categories, quality claims, time-sensitive words, other authors\' names, brands you don\'t own, Amazon program names',
          'Each keyword fits the character limit shown in KDP\'s keyword field',
          'Up to 3 categories chosen from KDP\'s own category list (not BISAC), matching your book as closely as possible',
        ],
        guides: [
          { href: '/kdp-keyword-guide', label: 'KDP keyword guide' },
          { href: '/amazon-keyword-research', label: 'Amazon keyword research for books' },
          { href: '/kdp-category-keywords', label: 'KDP categories and keywords' },
        ],
        paidTool: { slug: 'kdp-keyword-finder' },
        sources: [
          { label: 'KDP: keywords', url: 'https://kdp.amazon.com/en_US/help/topic/G201298500' },
          { label: 'KDP: categories', url: 'https://kdp.amazon.com/en_US/help/topic/G200652170' },
        ],
      },
      {
        heading: 'Pricing and rights',
        items: [
          'For the 70% royalty on Amazon.com, your list price is between $2.99 and $12.99',
          '70% royalties include a delivery cost based on file size ($0.15 per MB on Amazon.com)',
          'KDP Select decided: it is a 90-day program, and enrolled eBooks must be exclusive to KDP in digital form, including your own website',
          'Territory rights set to match the rights you hold',
        ],
        guides: [{ href: '/kdp-ebook-pricing', label: 'KDP ebook pricing guide' }],
        sources: [
          { label: 'KDP: eBook royalties', url: 'https://kdp.amazon.com/en_US/help/topic/G200634560' },
          { label: 'KDP: delivery costs', url: 'https://kdp.amazon.com/en_US/help/topic/G200634500' },
          { label: 'KDP Select', url: 'https://kdp.amazon.com/en_US/help/topic/G200798990' },
          { label: 'KDP Select exclusivity', url: 'https://kdp.amazon.com/en_US/select' },
        ],
      },
      {
        heading: 'Final upload',
        items: [
          'Book previewed in Kindle Previewer and checked page by page',
          'Table of contents opens from the Kindle navigation menu in the preview',
          'Timing planned: KDP says a new book can take up to 3 business days to go live',
          'After publishing, changes to details like keywords and description can take up to 72 hours to show',
        ],
        tools: [{ slug: 'publishing-score' }],
        sources: [
          { label: 'KDP: eBook manuscript formats (Kindle Previewer)', url: 'https://kdp.amazon.com/en_US/help/topic/G200634390' },
          { label: 'KDP: book status', url: 'https://kdp.amazon.com/en_US/help/topic/G200627450' },
          { label: 'KDP: timelines', url: 'https://kdp.amazon.com/en_US/help/topic/G202173620' },
        ],
      },
    ],
    faq: [
      {
        q: 'How long does KDP take to publish my book?',
        a: "KDP says a new book can take up to 3 business days to go live (KDP help G200627450). Changes to a live book's details, such as keywords or description, can take up to 72 hours to show (G202173620).",
      },
      {
        q: 'What file formats does KDP accept for eBooks?',
        a: 'KDP accepts Word (DOC/DOCX), KPF and EPUB, as well as HTML, RTF and TXT. PDF is supported only for some languages (KDP help G200634390). Files up to 650 MB can be uploaded (G200735140).',
      },
      {
        q: 'What size should my Kindle cover be?',
        a: "KDP's ideal eBook cover is 2,560 × 1,600 pixels (height × width), a 1.6:1 ratio, and the minimum is 1,000 × 625 pixels. Use a JPEG or TIFF file under 50 MB, in RGB color (KDP help G200645690).",
      },
      {
        q: 'How many keywords and categories can I add?',
        a: 'KDP lets you add up to 7 keywords or short phrases (KDP help G201298500) and select 3 categories from its own category list (G200652170).',
      },
      {
        q: 'Do I need an ISBN for a Kindle eBook?',
        a: 'No. An ISBN is optional for Kindle eBooks. Each print format, such as a paperback, needs its own ISBN (KDP help G201834170).',
      },
      {
        q: 'What price gets the 70% royalty?',
        a: 'On Amazon.com, a list price between $2.99 and $12.99 is eligible for the 70% royalty (KDP help G200634560). The 70% option includes a delivery cost based on file size (G200634500).',
      },
      {
        q: 'Do I have to disclose AI-generated content?',
        a: "Yes. KDP asks you to disclose AI-generated text, images or translations when you publish or republish. Content you wrote yourself and only edited or improved with AI tools is AI-assisted and doesn't need to be disclosed (KDP help G200672390).",
      },
      {
        q: 'Should I preview my book before uploading?',
        a: 'Yes. KDP recommends checking an EPUB with Kindle Previewer before you upload it (KDP help G200634390).',
      },
      {
        q: 'Is there a printable version of this checklist?',
        a: 'Yes. The same checklist is available as a free PDF — enter your email in the box on this page to get it.',
      },
    ],
    relatedTool: 'epub-validator',
    related: [
      { type: 'checklist', slug: 'epub-formatting-checklist', label: 'EPUB formatting checklist' },
      { type: 'guide', slug: 'kdp-formatting-guide', label: 'KDP formatting guide' },
      { type: 'cover-requirement', slug: 'amazon-kdp-ebook', label: 'Amazon KDP ebook cover requirements' },
      { type: 'guide', slug: 'kdp-ebook-pricing', label: 'KDP ebook pricing guide' },
      { type: 'platform-rejection', slug: 'amazon-kdp', label: 'Why Amazon KDP rejects ebooks' },
      { type: 'epub-error', slug: 'missing-ncx-navigation', label: 'Missing NCX navigation table' },
      { type: 'epub-error', slug: 'broken-spine-order', label: 'Broken spine order errors' },
      { type: 'epub-error', slug: 'cover-image-not-declared', label: 'Cover image not declared in OPF manifest' },
      { type: 'alternative', slug: 'scrivener-alternative', label: 'Scrivener alternative for ebook production' },
      { type: 'mistake', slug: 'kdp-formatting-mistakes', label: '7 KDP formatting mistakes indie authors make' },
      { type: 'guide', slug: 'kdp-quality-issues', label: 'KDP quality issues and quality notices' },
    ],
  },
  {
    slug: 'apple-books-submission-checklist',
    metaTitle: '21-Point Apple Books Submission Checklist — BookKraft AI',
    metaDescription: 'Apple Books upload checklist. These 21 points cover EPUBCheck compliance, ISBN requirements, cover color profiles, nav.xhtml structure, and rights declarations.',
    title: '21-Point Apple Books Submission Checklist',
    intro: '<p>Use this list as a pre-submission gate, not a post-rejection diagnostic. Work through each category before opening Apple Books Connect — most items in the File Validation and Navigation sections belong in your file-preparation workflow, not on the upload screen. The cover color mode check and the ISBN format in content.opf are the two Apple-specific requirements most commonly overlooked by authors publishing to KDP first and Apple Books second.</p>',
    sections: [
      {
        heading: 'File Validation',
        items: [
          'Run EPUBCheck 5.x on the final packaged EPUB and confirm the report shows zero Critical or Error-level issues — a clean report is a good baseline before Apple Books checks the file on upload',
          'Open each XHTML chapter file in a markup validator — Apple checks HTML compliance inside chapter documents, a step beyond standard OPF and manifest checking',
          'Search across all chapter files for duplicate id attributes and remove every duplicate before zipping the EPUB',
          'Scan all EPUB 3 content files for EPUB 2 vestiges such as opf:role attributes — mixed-version markup triggers Apple\'s schema validator',
          'Audit the CSS file for deprecated or non-standard properties. Apple says books must pass the latest version of EPUBCheck: fix every error it reports, and clearing warnings too is good practice',
        ],
      },
      {
        heading: 'Required Metadata',
        items: [
          'Add ISBN-13 to content.opf: <dc:identifier opf:scheme="ISBN">978...</dc:identifier> — paid submissions without a properly formatted ISBN are blocked at the intake stage',
          'Verify dc:title, dc:creator, and dc:language are populated in content.opf — empty fields are rejected even if the same data is entered in Apple Books Connect',
          'Write a minimum 50-word description in Apple Books Connect — below this the editorial review queue may flag for insufficient metadata',
          'Enter a publisher name in Apple Books Connect (required field in the Connect interface, independent of content.opf)',
          'Select subject/BISAC codes in Apple Books Connect — category assignment is mandatory before submission unlocks',
        ],
      },
      {
        heading: 'Cover File',
        items: [
          'Export the cover at least 1400 pixels on the shorter side — Apple\'s minimum for cover art',
          'Save as JPG or PNG in RGB color mode — CMYK output from print-production workflows is one of the most frequent Apple-specific rejection causes',
          'Save the cover in RGB. Apple names no color profile; embedding sRGB is a common choice — tools such as Affinity Publisher default to document profiles other than sRGB on export',
          'Confirm body images are JPG, PNG, or GIF and that each has a matching MIME type declaration in the OPF manifest',
        ],
      },
      {
        heading: 'Navigation & Structure',
        items: [
          'Confirm nav.xhtml exists and its <nav epub:type="toc"> element contains a properly nested ordered list of chapter links',
          'Check that nav.xhtml carries properties="nav" in the OPF manifest entry',
          'Include toc.ncx for backward compatibility with older Apple hardware running legacy iBooks builds',
          'Verify the OPF spine sequence: every idref points to a declared manifest item and the order matches intended reading order',
        ],
      },
      {
        heading: 'Rights & Distribution',
        items: [
          'Set territory rights in Apple Books Connect to match your actual rights scope — selecting Worldwide when rights are restricted triggers a rights conflict review',
          'Review the book against Apple\'s content guidelines before submitting — flags for explicit content or prohibited categories arrive as post-submission rejections, not upload errors',
          'If using an aggregator (Draft2Digital, Smashwords), verify the aggregator is not also configured to deliver to Apple Books — duplicate listings are removed, and the direct submission takes precedence',
        ],
      },
    ],
    faq: [
      {
        q: 'My EPUB passed EPUBCheck but Apple Books still rejected it — why?',
        a: "Apple validates against some Apple-specific schema rules beyond standard EPUBCheck, particularly for nav.xhtml structure, ISBN format, and cover image color profiles. The rejection email includes specific error codes — check those first. The three most common Apple-specific failures that pass EPUBCheck are: CMYK cover images, missing or incorrectly formatted ISBN-13, and nav.xhtml missing the epub:type attribute.",
      },
      {
        q: 'Is an ISBN required to publish on Apple Books?',
        a: "For paid books distributed directly through Apple Books Connect, yes — a valid ISBN-13 is required as the dc:identifier. For free books, Apple may accept a UUID-based identifier. If you don't have an ISBN, aggregators like Draft2Digital provide free ISBNs — though using a D2D ISBN means D2D manages the book's Apple Books listing, not you directly.",
      },
      {
        q: 'Does this checklist apply if I\'m distributing to Apple Books through Draft2Digital?',
        a: "Most items still apply — D2D runs its own pre-conversion validation before sending to Apple, and a file that fails Apple's requirements will be rejected regardless of how it was submitted. The Rights & Territory section is the main difference: D2D handles the Apple Books Connect account, so you set territory rights in D2D's interface rather than directly in Apple Books Connect.",
      },
    ],
    relatedTool: 'epub-validator',
    related: [
      { type: 'platform-rejection', slug: 'apple-books', label: 'Why Apple Books rejects ebooks' },
      { type: 'epub-error', slug: 'duplicate-id-epub', label: 'Duplicate ID attribute errors' },
      { type: 'epub-error', slug: 'missing-ncx-navigation', label: 'Missing NCX navigation table' },
      { type: 'epub-error', slug: 'malformed-xhtml-unclosed-tag', label: 'Malformed XHTML — unclosed tags in chapter files' },
      { type: 'alternative', slug: 'jutoh-alternative', label: 'Jutoh alternative for EPUB formatting' },
    ],
  },
  {
    slug: 'apple-books-pre-launch-checklist',
    metaTitle: '18-Point Apple Books Pre-Launch Checklist — BookKraft AI',
    metaDescription: 'Apple Books upload checklist. These 18 points cover EPUB 3 compliance, RGB covers, ISBN scheme, and the nav.xhtml requirements Apple checks at submission.',
    title: '18-Point Apple Books Pre-Launch Checklist',
    intro: '<p>A file that uploads to KDP without complaint can still be rejected by Apple Books Connect over cover color mode, ISBN format, or EPUB 3 structure. This checklist covers the Apple-specific requirements that go beyond generic EPUB validation. Complete the general EPUB formatting checklist first, then work through these.</p>',
    sections: [
      {
        heading: 'File & Structure',
        items: [
          'File is valid EPUB 3 — Apple Books requires EPUB 3, not EPUB 2',
          'nav.xhtml present with a valid <nav epub:type="toc"> element',
          'No EPUB 2 vestiges such as opf:role attributes in an EPUB 3 file',
          'All XHTML chapter files are well-formed — no unclosed tags or unescaped ampersands',
          'Zero EPUBCheck Error or Fatal results against the current specification',
        ],
      },
      {
        heading: 'Cover & Images',
        items: [
          'Cover image minimum 1400px × 2100px — higher than KDP\'s floor',
          'Cover is RGB, not CMYK',
          'Cover declared with properties="cover-image" in the OPF manifest',
          'All embedded images are JPEG or PNG in RGB, sized for screen',
        ],
      },
      {
        heading: 'Metadata',
        items: [
          'dc:identifier uses a valid ISBN with scheme="ISBN", or a UUID if no ISBN',
          'dc:title and dc:creator populated and matching the cover',
          'dc:language set to a valid BCP 47 code',
          'Publication date present and correctly formatted',
        ],
      },
      {
        heading: 'Submission',
        items: [
          'File previewed in Apple Books on a Mac or iOS device before submission',
          'Fixed-layout flag set correctly — only for image-heavy or picture books',
          'Accessibility metadata included: alt text on informative images, empty alt on decorative',
          'File size within Apple Books limits and images not excessively large',
          'A fresh EPUBCheck run passed on the exact file being submitted',
        ],
      },
    ],
    faq: [
      {
        q: 'Why does Apple Books reject a file that passed EPUBCheck?',
        a: 'Apple validates against Apple-specific rules beyond EPUBCheck — particularly CMYK cover images, ISBN format (scheme="ISBN" required), and nav.xhtml structure. The three most common Apple-specific failures that pass EPUBCheck are CMYK covers, missing or wrongly formatted ISBNs, and nav.xhtml missing the epub:type attribute.',
      },
      {
        q: 'Do I need an ISBN for Apple Books?',
        a: 'Apple Books does not strictly require an ISBN — a UUID identifier is accepted — but if you do include an ISBN, it must be declared with scheme="ISBN" in the dc:identifier. A malformed ISBN declaration is a common rejection cause.',
      },
      {
        q: 'How do I convert an EPUB 2 file to EPUB 3 for Apple Books?',
        a: 'Regenerate the file from your source with a tool that outputs EPUB 3, or run it through an EPUB formatter that upgrades the structure and adds a nav.xhtml. Manually patching an EPUB 2 file to EPUB 3 usually leaves EPUB 2 vestiges that Apple\'s validator flags.',
      },
    ],
    relatedTool: 'cover-checker',
    related: [
      { type: 'platform-rejection', slug: 'apple-books', label: 'Why Apple Books rejects ebooks' },
      { type: 'cover-requirement', slug: 'apple-books-ebook', label: 'Apple Books ebook cover requirements' },
      { type: 'checklist', slug: 'epub-formatting-checklist', label: 'EPUB formatting pre-upload checklist' },
      { type: 'epub-error', slug: 'opf-role-attribute-not-allowed', label: 'opf:role attribute not allowed (RSC-005)' },
    ],
  },
  {
    slug: 'print-book-pre-launch-checklist',
    metaTitle: '16-Point Print Book Pre-Launch Checklist — BookKraft AI',
    metaDescription: 'A print book pre-launch checklist for KDP Print and IngramSpark: PDF/X-1a export, CMYK, bleed, calculated spine width, embedded fonts, and interior margin checks before you submit.',
    title: '16-Point Print Book Pre-Launch Checklist',
    intro: '<p>Print books follow entirely different rules from ebooks — fixed pages, CMYK color, bleed, and a spine width calculated to your exact page count. This checklist covers the cover and interior requirements for KDP Print and IngramSpark.</p>',
    sections: [
      {
        heading: 'Interior File',
        items: [
          'Interior exported as PDF at 300 DPI with all fonts fully embedded (not subsetted)',
          'Trim size matches the size selected in the print dashboard exactly',
          'Inside (gutter) margins wide enough for the page count so text isn\'t swallowed by the binding',
          'No RGB images left in the interior — convert all to CMYK or grayscale',
          'Page count is even — print books require an even final page count',
        ],
      },
      {
        heading: 'Cover File',
        items: [
          'Full-wrap cover as a single PDF: back cover, spine, and front cover',
          'Exported as PDF/X-1a in CMYK color mode',
          '0.125 inch (3.175mm) bleed on all outer edges',
          'Spine width calculated from final page count and paper stock via the template generator',
          'Spine text kept clear of the fold with adequate margin (thin spines may not allow spine text)',
          'ISBN barcode on the back cover on a white box, not resized',
        ],
      },
      {
        heading: 'Proof & Submit',
        items: [
          'Fresh cover template downloaded after the final interior page count was set',
          'Digital proof reviewed page by page for reflowed text or shifted images',
          'A physical or online proof ordered and checked before approving distribution',
          'Metadata (title, author, ISBN) consistent between cover, interior, and dashboard',
          'No spot colors or PMS values — process CMYK only',
        ],
      },
    ],
    faq: [
      {
        q: 'Why does my print cover keep getting rejected at preflight?',
        a: 'The most common causes are an RGB or standard PDF instead of PDF/X-1a, an incorrect spine width from a stale template, missing bleed, or subsetted fonts. Check each of these against the cover section above before resubmitting.',
      },
      {
        q: 'How is the spine width determined?',
        a: 'Spine width is a function of page count and paper stock thickness. Use the print platform\'s cover template generator with your final page count and chosen paper — it outputs the exact spine width and canvas size. Any change to page count requires a new template.',
      },
      {
        q: 'Can I reuse my ebook cover for the print edition?',
        a: 'No. An ebook cover is a single RGB image of the front only. A print cover is a full-wrap CMYK PDF with back cover, spine, front, bleed, and a barcode area. The print cover must be built separately.',
      },
    ],
    relatedTool: 'cover-checker',
    related: [
      { type: 'cover-requirement', slug: 'ingramspark-print', label: 'IngramSpark print book cover requirements' },
      { type: 'platform-rejection', slug: 'ingram-spark', label: 'Why IngramSpark rejects books' },
      { type: 'mistake', slug: 'print-formatting-mistakes', label: '5 print book formatting mistakes that get covers rejected' },
      { type: 'checklist', slug: 'kdp-pre-launch-checklist', label: 'KDP preflight checklist' },
    ],
  },
  {
    slug: 'manuscript-cleanup-checklist',
    metaTitle: '15-Point Manuscript Cleanup Checklist Before Formatting — BookKraft AI',
    metaDescription: 'Clean your manuscript before you format it. This 15-point checklist covers double spaces, straight vs curly quotes, encoding artifacts, and the Word habits that break EPUB conversion.',
    title: '15-Point Manuscript Cleanup Checklist Before Formatting',
    intro: '<p>Most EPUB errors start life as habits in a Word document — double spaces, manual indents, empty paragraphs, and encoding artifacts that survive conversion and surface as validation errors or ugly rendering. Cleaning the manuscript before you format it prevents the majority of downstream problems. Work through this list on your source document first.</p>',
    sections: [
      {
        heading: 'Spacing & Characters',
        items: [
          'Double spaces removed — find-and-replace two spaces with one throughout',
          'Tabs and manual first-line indents removed — set indentation in the paragraph style instead',
          'Runs of empty paragraphs deleted — use page breaks and CSS spacing, not blank lines',
          'Straight quotes converted to curly quotes consistently, or left straight per house style — no mix',
          'Em dashes and en dashes used correctly, not double hyphens',
        ],
      },
      {
        heading: 'Encoding & Symbols',
        items: [
          'File saved as UTF-8',
          'Replacement characters (□) and mojibake strings (â€™) searched and fixed',
          'Zero-width spaces (U+200B) and byte-order marks removed',
          'Accented names and special symbols verified to display correctly',
        ],
      },
      {
        heading: 'Structure',
        items: [
          'Chapter titles styled as Heading 1, sub-sections as Heading 2 — not hand-formatted',
          '"Page break before" set on the chapter heading style so each chapter starts fresh',
          'Print-only elements removed: running headers, footers, and page numbers',
          'References to physical page numbers ("see page 112") replaced with links',
        ],
      },
      {
        heading: 'Final Pass',
        items: [
          'Front matter and back matter complete and in the right order',
          'Manuscript run through a cleanup tool to catch remaining artifacts before conversion',
        ],
      },
    ],
    faq: [
      {
        q: 'Why clean the manuscript before formatting instead of fixing the EPUB later?',
        a: 'Artifacts like double spaces, straight quotes, and encoding errors get baked into every chapter file when the manuscript is converted. Fixing them once at the source is far faster than hunting them down across dozens of XHTML files afterward, and it prevents validation errors before they exist.',
      },
      {
        q: 'What is the fastest way to clean a Word manuscript?',
        a: 'Run it through a dedicated cleanup tool that catches smart quotes, double spaces, dashes, and encoding artifacts in a single pass, then do a manual check of headings and special characters. This is much faster and more reliable than find-and-replace alone.',
      },
      {
        q: 'Do I still need to clean the manuscript if I use a formatting tool?',
        a: 'Yes. Formatting tools handle structure and conversion, but they generally preserve the text you give them. Garbage in, garbage out — a clean manuscript produces a clean EPUB, while a messy one carries its problems into the file.',
      },
    ],
    relatedTool: 'kindle-format-fixer',
    related: [
      { type: 'mistake', slug: 'epub-formatting-mistakes', label: '10 EPUB formatting mistakes that cause rejection' },
      { type: 'epub-error', slug: 'ghost-spacing-epub', label: 'Ghost spacing in e-reader previews' },
      { type: 'checklist', slug: 'epub-formatting-checklist', label: 'EPUB formatting pre-upload checklist' },
      { type: 'epub-error', slug: 'unescaped-ampersand-xhtml', label: 'Unescaped ampersand in XHTML' },
    ],
  },
  {
    slug: 'metadata-setup-checklist',
    metaTitle: '14-Point Book Metadata Setup Checklist — BookKraft AI',
    metaDescription: 'Set your book metadata up for discoverability and clean uploads. This 14-point checklist covers title matching, identifiers, language codes, keywords, categories, and description formatting.',
    title: '14-Point Book Metadata Setup Checklist',
    intro: '<p>Metadata decides whether your book uploads cleanly, displays correctly, and reaches the readers searching for it. It spans two places: the fields inside the EPUB file and the fields you fill in on the store dashboard. This checklist covers both so the file passes validation and the listing works for discovery.</p>',
    sections: [
      {
        heading: 'In-File Metadata (content.opf)',
        items: [
          'dc:title populated and non-empty, matching the cover exactly',
          'dc:creator populated with the author name',
          'dc:language set to a valid BCP 47 code (e.g., en or en-US)',
          'dc:identifier present — a valid ISBN-13 or a UUID',
          'Package unique-identifier attribute points to the dc:identifier id by name',
        ],
      },
      {
        heading: 'Store Listing',
        items: [
          'Title and subtitle match the cover word for word, including order',
          'Author name matches your existing Author Page to consolidate your profile',
          'Keywords use specific words in a logical order (KDP allows up to 7 keywords or short phrases)',
          'Categories chosen: up to 3 from KDP\'s own category list (not BISAC), plus BISAC codes for IngramSpark and other distributors that use them',
          'Series name and number set consistently if part of a series',
        ],
      },
      {
        heading: 'Description',
        items: [
          'Bold hook as the first line, above the "Read more" fold',
          'Short paragraphs with spacing, and 3–5 benefit bullets',
          'HTML formatting verified to render cleanly — no raw tags visible to readers',
          'No keyword stuffing — discoverability handled by keywords and categories, not the description',
        ],
      },
    ],
    faq: [
      {
        q: 'Where does metadata live — in the file or on the store?',
        a: 'Both. The EPUB carries in-file metadata (title, author, language, identifier) that validators and reading systems read, and the store dashboard has its own listing metadata (keywords, categories, description). They should agree with each other, especially the title.',
      },
      {
        q: 'How many keywords and categories should I set?',
        a: 'KDP lets you add up to seven keywords or short phrases and select up to 3 categories from its own category list (KDP doesn\'t use BISAC). For keywords, use specific words in a logical order; for categories, pick the ones that match your book most closely.',
      },
      {
        q: 'Can I edit metadata after publishing?',
        a: 'Listing metadata — description, keywords, categories — can be edited in the dashboard after publication and updates within hours. In-file metadata requires re-uploading a corrected EPUB. The cover title must always continue to match the metadata title.',
      },
    ],
    relatedTool: 'metadata-builder',
    related: [
      { type: 'mistake', slug: 'book-metadata-mistakes', label: '6 book metadata mistakes that hurt discoverability' },
      { type: 'epub-error', slug: 'unique-identifier-not-found', label: 'Unique identifier not found (OPF-048)' },
      { type: 'checklist', slug: 'kdp-pre-launch-checklist', label: 'KDP preflight checklist' },
      { type: 'platform-rejection', slug: 'amazon-kdp', label: 'Why Amazon KDP rejects ebooks' },
    ],
  },
  {
    slug: 'book-launch-day-checklist',
    metaTitle: '15-Point Book Launch Day Checklist — BookKraft AI',
    metaDescription: 'A book launch day checklist that starts after the file passes validation: final listing checks, pricing, categories, review copies, and the first-week actions that build momentum.',
    title: '15-Point Book Launch Day Checklist',
    intro: '<p>Your file is validated and your metadata is set — now comes the launch. This checklist picks up where the technical work ends and covers the listing, pricing, and promotion steps that decide whether a book lands with momentum or silence. Work through it in the days around your publish date.</p>',
    sections: [
      {
        heading: 'Final Listing Check',
        items: [
          'Cover title, subtitle, and author name match the metadata exactly, word for word',
          'Description formatted with a bold hook, short paragraphs, and clean HTML — no raw tags visible',
          'All 7 keyword slots filled with long-tail reader search phrases',
          'Up to 3 KDP categories selected from KDP\'s own list (not BISAC), matching your book as closely as possible',
          'Preview checked on phone, tablet, and e-reader in Kindle Previewer',
        ],
      },
      {
        heading: 'Pricing & Distribution',
        items: [
          'Launch price set, with any introductory discount scheduled and dated',
          'KDP Select exclusivity decision made — confirm the book is not live elsewhere if enrolling',
          'Territories and royalty rate (35% vs 70%) reviewed for each marketplace',
          'Pre-order configured if launching later, or "publish now" confirmed',
        ],
      },
      {
        heading: 'Launch & First Week',
        items: [
          'Advance review copies sent to your early readers and street team',
          'Author Central profile and Author Page updated with the new title',
          'Launch announcement scheduled for your mailing list and social channels',
          'Back matter links (Also By, mailing list CTA) confirmed working in the live file',
          'A plan in place to request honest reviews from readers in the first two weeks',
          'Sales dashboard checked 48 hours after launch for reporting or listing errors',
        ],
      },
    ],
    faq: [
      {
        q: 'Should I launch at full price or with a discount?',
        a: 'A time-limited introductory price (often 99 cents or free via KDP Select) can drive early downloads and reviews that improve visibility, then rise to full price. The right choice depends on your genre and whether you are running launch promotion to take advantage of the lower price.',
      },
      {
        q: 'How important are reviews in the first week?',
        a: 'Early reviews build credibility and feed Amazon\'s recommendation systems. Line up honest reviews from advance readers before launch, and make a clear ask to buyers in your back matter and mailing list. Never buy reviews — Amazon removes them and can penalize the account.',
      },
      {
        q: 'Can I fix listing mistakes after launching?',
        a: 'Yes. Description, keywords, categories, and price can all be edited in the dashboard after publication and update within hours. The cover and interior require re-uploading a corrected file. Check the live listing within 48 hours to catch anything that didn\'t save correctly.',
      },
    ],
    relatedTool: 'kdp-keyword-finder',
    related: [
      { type: 'checklist', slug: 'metadata-setup-checklist', label: 'Book metadata setup checklist' },
      { type: 'checklist', slug: 'kdp-pre-launch-checklist', label: 'KDP preflight checklist' },
      { type: 'mistake', slug: 'book-metadata-mistakes', label: '6 book metadata mistakes that hurt discoverability' },
      { type: 'platform-rejection', slug: 'amazon-kdp', label: 'Why Amazon KDP rejects ebooks' },
    ],
  },
];

export function getChecklistBySlug(slug) {
  return CHECKLISTS.find((c) => c.slug === slug) ?? null;
}
