// BookKraft AI v8.0 — 16 eBook Formatting Tool Definitions (derive counts from TOOLS.length, don't hardcode)

export const TOOLS = [
    // ── FORMATTING CATEGORY ──────────────────────────────────────────────
    {
        slug: 'kindle-format-fixer',
        name: 'Kindle Format Fixer',
        seoTitle: 'Kindle Format Fixer for KDP — Fix Smart Quotes, Em Dashes & Encoding',
        h1: 'Kindle Format Fixer for KDP and EPUB',
        seoContent: `<h2>What Does a Kindle Format Fixer Do?</h2><p>When you write a manuscript in Word or Google Docs and export it, the file often carries hidden formatting problems: straight quotes instead of curly ones, double hyphens instead of proper em dashes, doubled-up spaces from old typing habits, and garbled characters from encoding mismatches. None of these show up clearly when you're writing. They show up after you upload to KDP, when your book looks unprofessional or triggers a formatting warning.</p><p>This free tool scans your pasted text and fixes all of these issues at once, instantly, in your browser.</p><h2>Why Smart Quotes and Em Dashes Matter</h2><p>Straight quotes (&quot;like this&quot;) read as amateur to readers used to professionally typeset books. Curly quotes (&ldquo;like this&rdquo;) are the standard in every published book. The same goes for em dashes — a double hyphen (--) looks like a typo, while a proper em dash (—) reads as intentional, polished prose. These are small details, but they're exactly the kind of detail that separates a manuscript that looks self-published from one that looks professionally produced.</p><h2>How to Use the Kindle Format Fixer</h2><p>Paste your manuscript text into the input box. The tool fixes smart quotes, em dashes, double spaces, tab indents, line breaks, blank lines, stray HTML, and encoding artifacts automatically, all toggleable individually if you only want some fixes applied. Copy the result or download it as a .txt file. No signup, no upload limit, no software install.</p><h2>Common Word Export Errors This Tool Catches</h2><p>The most frequent issues found in manuscripts exported from Word or Google Docs are: straight quotes left unconverted, double-hyphen dashes instead of em dashes, doubled spaces between sentences, tab characters instead of proper paragraph indents, inconsistent line endings between Windows and Mac systems, three or more blank lines stacked together from copy-paste, leftover HTML tags from web-based editors, and mojibake — garbled accented characters caused by encoding mismatches between systems.</p><h2>Manual Cleanup vs. Automated Fixing</h2><p>Fixing these issues manually with Find &amp; Replace in Word works, but it's slow and easy to miss instances, especially in a full-length manuscript. This tool runs all eight fixes in a single pass and shows you exactly what was changed and how many instances of each issue were found, so you can verify the cleanup before publishing.</p><h2>Who This Tool Is For</h2><p>Self-publishing authors preparing a manuscript for KDP upload, anyone converting a Word or Google Docs file to EPUB, freelance editors doing a final formatting pass before delivery, and writers who paste text between multiple tools and pick up stray formatting along the way. Works in any browser, on Windows, Mac, or Linux.</p><script type="application/ld+json">{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"Is the Kindle Format Fixer free?","acceptedAnswer":{"@type":"Answer","text":"Yes, completely free. No signup, no credit card, no account required. Unlimited use."}},{"@type":"Question","name":"Does my manuscript get uploaded to a server?","acceptedAnswer":{"@type":"Answer","text":"No. The tool runs entirely in your browser. Your text never leaves your device."}},{"@type":"Question","name":"What formatting errors does this tool fix?","acceptedAnswer":{"@type":"Answer","text":"It fixes eight common issues: smart quotes, em dashes, double spaces, tab indents, inconsistent line breaks, excessive blank lines, stray HTML tags, and encoding artifacts from Word or Google Docs exports."}},{"@type":"Question","name":"Will this work for both Kindle and EPUB formatting?","acceptedAnswer":{"@type":"Answer","text":"Yes. The fixes apply to plain text and carry over cleanly whether you're formatting for Kindle KDP, EPUB, or any other ebook platform."}}]}</script>`,
        category: 'formatting',
        desc: 'Fix smart quotes, em dashes, double spaces, and encoding errors from Word or Google Docs exports. Formats your manuscript for Kindle KDP or EPUB instantly. No software needed.',
        type: 'logic',
        accessType: 'logic',
        creditCost: 0,
        free: false,
        upsell: { text: 'Text cleaned. Build your TOC →', tool: 'toc-generator' },
        fields: [
            { id: 'text', label: 'Paste your manuscript text here', type: 'textarea', placeholder: 'Paste your text...' },
            {
                id: 'target', label: 'Format target', type: 'radio',
                options: [
                    { label: 'Kindle (KDP)', value: 'kindle' },
                    { label: 'EPUB', value: 'epub' },
                    { label: 'Both', value: 'both' },
                ],
            },
            {
                id: 'fixes', label: 'Fixes to apply', type: 'checkboxes', defaults: true,
                options: [
                    { id: 'smartQuotes', label: 'Fix smart quotes (straight → curly)' },
                    { id: 'emDashes', label: 'Fix em dashes (-- → —)' },
                    { id: 'doubleSpaces', label: 'Remove double spaces' },
                    { id: 'tabIndents', label: 'Convert tab indents to paragraph indent' },
                    { id: 'lineBreaks', label: 'Normalize line breaks (CRLF/CR → LF)' },
                    { id: 'doubleBlankLines', label: 'Remove double blank lines' },
                    { id: 'stripHtml', label: 'Strip HTML tags (for Word paste)' },
                    { id: 'fixEncoding', label: 'Fix encoding artifacts (â€™ → \' etc.)' },
                ],
            },
        ],
    },
    {
        slug: 'epub-formatter',
        name: 'EPUB Formatter',
        seoTitle: 'EPUB Formatter — Convert to EPUB 3.0 for KDP',
        h1: 'EPUB Formatter — Convert Your Manuscript to EPUB 3.0',
        intro: 'EPUB formatter for indie authors. Paste your manuscript and generate a valid EPUB 3.0 file with correct chapter structure, metadata, and cover image — no Sigil, no Calibre, no coding required. Included in Starter and Pro plans.',
        category: 'formatting',
        desc: 'Generate a valid EPUB 3.0 file directly from your manuscript. Handles chapter breaks, metadata, cover image embedding, and file structure automatically. No software or coding needed.',
        type: 'logic',
        accessType: 'logic',
        creditCost: 0,
        free: false,
        seoContent: `<h2>EPUB Formatter for Indie Authors</h2><p>Creating a valid EPUB file from scratch requires coding knowledge most authors don't have. This tool takes your manuscript and generates a properly structured EPUB 3.0 file automatically.</p><h2>DOCX to EPUB Converter — No Sigil or Calibre Required</h2><p>Takes your manuscript text and converts it into a valid EPUB 3.0 file. Handles chapter detection, metadata, cover image embedding, and file structure automatically. No Sigil, no Calibre, no coding required.</p><h2>Who This Is For</h2><p>Authors publishing to Apple Books, Kobo, or Google Play where EPUB is the required format. Anyone who finds Calibre too complicated. Formatters who want to deliver EPUB files quickly without manual coding.</p><h2>Convert Your Manuscript to EPUB 3.0 in 3 Steps</h2><p>Paste your manuscript, enter your book title and author name, upload a cover image if you have one, and download your EPUB file. The tool handles chapter breaks based on your heading style.</p><script type="application/ld+json">{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"Is the EPUB Formatter free?","acceptedAnswer":{"@type":"Answer","text":"It is a logic tool included in the Starter and Pro plans. No AI credits are used."}},{"@type":"Question","name":"Do I need Calibre or Sigil to make an EPUB?","acceptedAnswer":{"@type":"Answer","text":"No. This tool generates a valid EPUB 3.0 file directly from your manuscript text without any external software."}},{"@type":"Question","name":"Does it handle chapter breaks automatically?","acceptedAnswer":{"@type":"Answer","text":"Yes. The tool detects chapter breaks based on your heading style and structures the EPUB accordingly."}},{"@type":"Question","name":"Can I add a cover image?","acceptedAnswer":{"@type":"Answer","text":"Yes. Upload a cover image during the process and it gets embedded directly into the EPUB file."}},{"@type":"Question","name":"My manuscript is in Google Docs — does that affect anything?","acceptedAnswer":{"@type":"Answer","text":"No. Paste your text from any source — Google Docs, Word, Scrivener, or plain text. The tool works from pasted text, not uploaded files, so the source editor doesn't matter."}},{"@type":"Question","name":"Will the EPUB it generates pass validation on KDP or Apple Books?","acceptedAnswer":{"@type":"Answer","text":"It generates a valid EPUB 3.0 file, but every manuscript is different. Run your output through the free EPUB Validator before uploading — it checks structure, metadata, and navigation issues specific to your file in seconds."}}]}</script>`,
        upsell: { text: 'Download complete. Validate before uploading →', tool: 'epub-validator' },
        fields: [
            { id: 'manuscript', label: 'Paste your manuscript (use # for chapter headings)', type: 'textarea', placeholder: 'Chapter 1: The Beginning\n\nYour text here...' },
            { id: 'title', label: 'Book title', type: 'text', placeholder: 'My Book', required: true },
            { id: 'author', label: 'Author name', type: 'text', placeholder: 'Jane Doe', required: true },
            {
                id: 'language', label: 'Language', type: 'select',
                options: ['English', 'Spanish', 'French', 'German', 'Portuguese', 'Italian', 'Dutch'],
            },
            { id: 'isbn', label: 'ISBN (optional)', type: 'text', placeholder: 'Leave blank if you don\'t have one' },
            { id: 'cover', label: 'Cover image (optional, JPG/PNG, max 5MB)', type: 'file', accept: 'image/jpeg,image/png' },
            {
                id: 'headingDetection', label: 'Heading detection', type: 'radio',
                options: [
                    { label: 'Auto-detect headings', value: 'auto' },
                    { label: 'Lines starting with #', value: 'hash' },
                    { label: 'All-caps lines', value: 'caps' },
                ],
            },
        ],
    },
    {
        slug: 'toc-generator',
        name: 'TOC Generator',
        seoTitle: 'Table of Contents Generator for Kindle & EPUB — Free',
        h1: 'Table of Contents Generator for Kindle and EPUB',
        intro: 'Free Table of Contents Generator for Kindle, EPUB3, and NCX formats. Paste your chapter headings and get a correctly structured, clickable TOC ready to publish — no signup, no coding required.',
        category: 'formatting',
        desc: 'Build a clickable, correctly formatted Table of Contents for Kindle, EPUB3, and NCX. Paste your chapter headings and get clean, publish-ready TOC code in seconds. No signup needed.',
        type: 'logic',
        accessType: 'logic',
        creditCost: 0,
        free: false,
        seoContent: `<h2>Table of Contents Generator for Kindle and EPUB</h2><p>KDP requires a specific TOC format for Kindle books. Get it wrong and your book fails quality review. This tool generates the correct code for Kindle HTML, EPUB3 nav.xhtml, and NCX formats.</p><h2>Kindle and EPUB3 Table of Contents Code, Auto-Generated</h2><p>Clickable TOC in Kindle HTML format ready to paste into your manuscript. EPUB3 nav.xhtml for Apple Books and Kobo. NCX XML for older EPUB readers. Plain text TOC for print editions. Supports H1, H2, and H3 heading levels.</p><h2>Who This Is For</h2><p>Authors formatting their own books for KDP without hiring a formatter. Anyone who has had a book rejected for TOC errors. Formatters who want to generate clean TOC code without hand-coding it.</p><h2>Build a Clickable TOC From Your Chapter Headings</h2><p>Paste your manuscript or just your chapter headings, select which heading levels to include, choose your output format, and copy the generated TOC code directly into your file.</p><script type="application/ld+json">{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"Is the TOC Generator free to use?","acceptedAnswer":{"@type":"Answer","text":"It is a logic tool included in the Starter and Pro plans. No AI credits are used."}},{"@type":"Question","name":"Do I paste my entire manuscript, or just my chapter headings?","acceptedAnswer":{"@type":"Answer","text":"Either works. Paste the full manuscript and the tool extracts headings automatically, or paste just your chapter titles — one per line — if you want direct control over what appears in the TOC."}},{"@type":"Question","name":"What do I do with the generated TOC code?","acceptedAnswer":{"@type":"Answer","text":"Copy the output and paste it into the correct location in your manuscript file. For Kindle HTML, it goes near the front of your HTML file. For EPUB3 nav.xhtml, it replaces or becomes your navigation document. For NCX XML, it replaces your toc.ncx file."}},{"@type":"Question","name":"My chapters don't use standard heading styles — will it still detect them?","acceptedAnswer":{"@type":"Answer","text":"Yes. Use the heading detection options: auto-detect for standard heading styles, # prefix for chapters marked with a hash symbol, or all-caps lines if your headings are written in capitals. Pick whichever matches your manuscript."}},{"@type":"Question","name":"My book has parts and chapters — can it handle a nested table of contents?","acceptedAnswer":{"@type":"Answer","text":"Yes. H1, H2, and H3 levels are all supported and can be toggled independently. Use H1 for parts, H2 for chapters, and H3 for sections to get a properly nested TOC."}},{"@type":"Question","name":"Does it work for books with titled chapters instead of numbered ones?","acceptedAnswer":{"@type":"Answer","text":"Yes. The tool uses whatever text your headings contain — Chapter 1, The Storm, Part Two: The Reckoning — any heading text works as a TOC entry."}},{"@type":"Question","name":"I'm using Vellum or Scrivener — do I still need this?","acceptedAnswer":{"@type":"Answer","text":"Vellum and Scrivener generate TOCs automatically when you compile your manuscript. Use this tool if you're formatting manually, fixing a pre-existing EPUB file, or if your Kindle upload was rejected for a TOC error that you need to rebuild from scratch."}}]}</script>`,
        upsell: { text: 'TOC ready. Now generate your front matter pages →', tool: 'front-matter-generator' },
        fields: [
            { id: 'text', label: 'Paste your manuscript or chapter headings (one per line)', type: 'textarea', placeholder: 'Chapter 1: Beginning\nChapter 2: The Journey\n...' },
            {
                id: 'levels', label: 'Heading levels to include', type: 'checkboxes', defaults: true,
                options: [
                    { id: 'h1', label: 'H1 (chapters)' },
                    { id: 'h2', label: 'H2 (sections)' },
                    { id: 'h3', label: 'H3 (subsections)' },
                ],
            },
            {
                id: 'format', label: 'Output format', type: 'tabs',
                options: ['Kindle HTML', 'EPUB3 nav.xhtml', 'NCX XML', 'Plain Text'],
            },
            {
                id: 'prefix', label: 'Prefix style', type: 'radio',
                options: [
                    { label: 'Chapter 1:', value: 'chapter' },
                    { label: 'Part I:', value: 'part' },
                    { label: 'None', value: 'none' },
                ],
            },
        ],
    },
    {
        slug: 'manuscript-cleanup',
        name: 'Manuscript Cleanup',
        seoTitle: 'AI Manuscript Cleanup — Dialogue, Repetition & Cliché Checker',
        h1: 'AI Manuscript Cleanup for Authors',
        category: 'formatting',
        desc: 'AI-powered manuscript cleanup that catches dialogue punctuation errors, repeated words, and clichés that basic spell checkers always miss. Works for fiction and non-fiction — any length, full novels included.',
        type: 'ai',
        accessType: 'ai',
        creditCost: 1,
        free: false,
        hasSample: true,
        seoContent: `<h2>AI Manuscript Cleanup for Authors</h2><p>Spell checkers miss the errors that actually matter — repeated words, dialogue punctuation mistakes, and clichés that weaken your prose. This tool catches what basic tools don't.</p><h2>AI Manuscript Editing Software for Dialogue and Repetition Errors</h2><p>Repeated words used too close together. Clichés that weaken your writing. Dialogue punctuation errors like missing commas before dialogue tags. Paragraph spacing issues. Works for both fiction and non-fiction manuscripts.</p><h2>Who This Is For</h2><p>Authors who want a clean manuscript before sending to a human editor. Writers self-editing their first draft. Anyone who has had an editor return a manuscript full of the same repeated corrections.</p><h2>Self-Edit Your Manuscript Before Sending to a Human Editor</h2><p>Paste any length manuscript — a full novel included — choose light or deep cleanup mode, select your genre, and get a marked-up version showing every issue found with suggested fixes. Longer manuscripts are split by chapter and processed in the background with live progress.</p><script type="application/ld+json">{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"Is there a free trial before I use credits?","acceptedAnswer":{"@type":"Answer","text":"Yes. A free 500-word sample is available so you can see the output quality before committing any credits. Run the sample first on a representative section of your manuscript."}},{"@type":"Question","name":"Will it rewrite my sentences, or does it only flag issues?","acceptedAnswer":{"@type":"Answer","text":"It flags issues and suggests fixes — it does not rewrite your prose. You review every suggested change and decide what to accept. Your voice and sentence structure stay exactly as you wrote them."}},{"@type":"Question","name":"What's the difference between Light and Deep cleanup mode?","acceptedAnswer":{"@type":"Answer","text":"Light mode handles formatting only — paragraph spacing, line breaks, punctuation mechanics. Deep mode adds prose-level checks: repeated words used too close together, weak clichés, and dialogue punctuation errors that slip past spell checkers."}},{"@type":"Question","name":"How many credits does a full novel cost?","acceptedAnswer":{"@type":"Answer","text":"Cost scales with word count and is shown before you confirm the run, so you always know the cost upfront. A 500-word free sample is available first so you can judge the output quality before spending any credits."}},{"@type":"Question","name":"Does it catch dialogue punctuation errors specifically?","acceptedAnswer":{"@type":"Answer","text":"Yes — dialogue punctuation is one of its strongest checks. It catches missing commas before dialogue tags, incorrect capitalization after a comma-separated tag, and inconsistent quote style, all of which spell checkers routinely miss."}},{"@type":"Question","name":"Will it work on non-fiction, or is it built for fiction?","acceptedAnswer":{"@type":"Answer","text":"It works for both. The genre selector adjusts which checks are prioritized — fiction mode focuses on dialogue and repetition, non-fiction mode focuses on paragraph spacing, formatting consistency, and structural issues."}},{"@type":"Question","name":"Can I use it on poetry or screenplays?","acceptedAnswer":{"@type":"Answer","text":"It's optimized for prose — fiction novels and non-fiction manuscripts. Poetry and scripts have conventions that would trigger false positives. It's not recommended for those formats."}}]}</script>`,
        upsell: { text: 'Manuscript cleaned. Now check style consistency →', tool: 'style-sheet-auditor' },
        fields: [
            { id: 'text', label: 'Paste your manuscript (any length)', type: 'textarea', placeholder: 'Paste your manuscript text here...' },
            {
                id: 'mode', label: 'Cleanup mode', type: 'radio',
                options: [
                    { label: 'Light — formatting only', value: 'light' },
                    { label: 'Deep — formatting + prose issues', value: 'deep' },
                ],
            },
            {
                id: 'genre', label: 'Genre', type: 'radio',
                options: [
                    { label: 'Fiction', value: 'fiction' },
                    { label: 'Non-fiction', value: 'nonfiction' },
                ],
            },
            {
                id: 'checks', label: 'Checks to apply', type: 'checkboxes', defaults: true,
                options: [
                    { id: 'repeatedWords', label: 'Flag repeated words (within 200 words)' },
                    { id: 'cliches', label: 'Flag clichés' },
                    { id: 'dialoguePunct', label: 'Fix dialogue punctuation' },
                    { id: 'paragraphSpacing', label: 'Fix paragraph spacing' },
                ],
            },
        ],
    },
    {
        slug: 'print-to-digital',
        name: 'Print-to-Digital Adapter',
        seoTitle: 'Print-to-Digital Converter for KDP and EPUB',
        h1: 'Print-to-Digital Converter for KDP and EPUB Books',
        intro: 'Convert print-formatted manuscripts to eBook-ready text for KDP and EPUB. This print-to-digital converter handles page references, footnotes, running headers, and fixed-width tables automatically — any manuscript length, no manual search and replace.',
        category: 'formatting',
        desc: 'Convert print-specific elements like page references, footnotes, and running headers into eBook-ready format using AI. Works for KDP and EPUB — any manuscript length.',
        type: 'ai',
        accessType: 'ai',
        creditCost: 1,
        free: false,
        seoContent: `<h2>Print to Digital Converter for Authors</h2><p>Print books contain elements that break in eBook format — page references, footnotes, running headers, and fixed-width tables. Converting them manually takes hours. This tool handles it automatically.</p><h2>What It Converts</h2><p>Page references like "see page 42" converted to chapter references. Footnotes moved to endnotes or inline parentheticals. Running headers removed. Fixed-width table descriptions rewritten for reflowable text. Figure references updated for digital format.</p><h2>Who This Is For</h2><p>Authors converting an existing print book to eBook format. Publishers bringing backlist titles to digital. Formatters converting academic or non-fiction titles with heavy footnote usage.</p><h2>How to Use It</h2><p>Paste your print-formatted text — any length, full manuscript included — select which elements to convert, choose your footnote format, confirm the cost, and get eBook-ready text back. Longer manuscripts are split by chapter and processed in the background with live progress.</p><script type="application/ld+json">{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"Is there a word limit?","acceptedAnswer":{"@type":"Answer","text":"No. Full-length manuscripts are automatically split into chapters and processed in the background. The cost scales with word count and is shown before you confirm the run, so you always know what you're spending before it starts."}},{"@type":"Question","name":"Will it change my actual prose — sentences, paragraphs, or content?","acceptedAnswer":{"@type":"Answer","text":"Only the elements you select are touched. If you enable footnote conversion, footnotes are moved. If you enable page reference conversion, those phrases are updated. Everything else — your sentences, arguments, and narrative — stays exactly as written."}},{"@type":"Question","name":"What do I actually get back, and how do I use the output?","acceptedAnswer":{"@type":"Answer","text":"You get your full manuscript text returned with the selected elements converted. Copy the output and paste it back into your manuscript file or EPUB editor. The tool doesn't produce a formatted EPUB file — it prepares your text so the next formatting step works correctly."}},{"@type":"Question","name":"My book only has a handful of page references — is this still worth running?","acceptedAnswer":{"@type":"Answer","text":"Yes. Even a few 'see page 42' references will break the reading experience on an eReader where page numbers don't exist. Running the tool even for a light manuscript cleans those references reliably without hunting for them manually."}},{"@type":"Question","name":"Can I choose what happens to my footnotes — endnotes or inline?","acceptedAnswer":{"@type":"Answer","text":"Yes. Three footnote formats are available: endnotes collected at the back of the book, inline parentheticals inserted into the running text, and EPUB3 pop-ups that appear as clickable overlays on compatible readers."}},{"@type":"Question","name":"What about data tables — does it convert those?","acceptedAnswer":{"@type":"Answer","text":"The table conversion rewrites fixed-width print table descriptions into reflowable prose descriptions. It does not convert data tables to HTML table elements — complex data tables need to be handled manually in your EPUB editor after running this tool."}},{"@type":"Question","name":"Can I run it on individual chapters instead of the full manuscript?","acceptedAnswer":{"@type":"Answer","text":"Yes. Paste as much or as little as you need. Processing chapter by chapter can help if you want to review changes section by section, especially for academic manuscripts where footnote placement decisions vary by chapter."}}]}</script>`,
        upsell: { text: 'Conversion complete. Validate your EPUB after formatting →', tool: 'epub-validator' },
        fields: [
            { id: 'text', label: 'Paste your print-format text (any length)', type: 'textarea', placeholder: 'Paste your print text here...' },
            {
                id: 'adaptations', label: 'Elements to adapt', type: 'checkboxes', defaults: true,
                options: [
                    { id: 'pageRefs', label: 'Page references ("see page X" → "see Chapter X")' },
                    { id: 'footnotes', label: 'Footnotes' },
                    { id: 'runningHeaders', label: 'Running headers' },
                    { id: 'tables', label: 'Fixed-width table descriptions' },
                    { id: 'figureRefs', label: '"See figure X" references' },
                ],
            },
            {
                id: 'footnoteFormat', label: 'Footnote format', type: 'radio',
                options: [
                    { label: 'Endnotes', value: 'endnotes' },
                    { label: 'Inline parenthetical', value: 'inline' },
                    { label: 'EPUB3 pop-ups', value: 'popup' },
                ],
            },
        ],
    },

    // ── STRUCTURE CATEGORY ──────────────────────────────────────────────
    {
        slug: 'front-matter-generator',
        name: 'Front Matter Generator',
        seoTitle: 'Front Matter Generator for Books — KDP Title Page & Copyright Page',
        h1: 'Front Matter Generator for KDP and EPUB Books',
        intro: 'Front Matter Generator for indie authors. Fill out a form and get a professional title page, copyright page, dedication, and disclaimer formatted to KDP and EPUB standards — no formatting experience needed.',
        category: 'structure',
        desc: 'Generate a professional title page, copyright page, dedication, and disclaimer for your book. Fill out a simple form and get publish-ready front matter for KDP instantly.',
        type: 'logic',
        accessType: 'logic',
        creditCost: 0,
        free: false,
        seoContent: `<h2>Front Matter Generator for Books</h2><p>Front matter is the first thing a reader sees when they open your book. Done wrong, it looks unprofessional. Done right, it signals that you take your work seriously. This tool generates every front matter section in the correct format for KDP and other platforms.</p><h2>What This Tool Generates</h2><p>Title page with your book title, subtitle, and author name formatted correctly. Copyright page with the right legal language, your ISBN, publisher name, and edition. Dedication page ready to personalize. Disclaimer page for fiction, health, finance, or general nonfiction books. Each section follows standard publishing conventions.</p><h2>Why Front Matter Formatting Matters</h2><p>KDP has specific requirements for how front matter should be structured. A title page that looks off or a copyright page missing key details can make your book look self-published in the wrong way. Readers notice these things even when they don't realize it.</p><h2>Who This Is For</h2><p>First-time authors who don't know what goes in a copyright page. Experienced authors who want to stop writing the same boilerplate for every book. Editors who want to deliver complete manuscripts to clients without spending extra time on formatting.</p><script type="application/ld+json">{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"Is this tool free to use?","acceptedAnswer":{"@type":"Answer","text":"It is a logic tool included in the Starter and Pro plans. No AI credits are used — generate as many times as you need."}},{"@type":"Question","name":"What do I get back — formatted HTML, plain text, or something else?","acceptedAnswer":{"@type":"Answer","text":"You get formatted text ready to paste directly into your manuscript. Each section is output in clean, publish-ready format. If you're building an EPUB, paste it into the appropriate XHTML file. If you're using KDP's manuscript editor, paste it at the front of your document."}},{"@type":"Question","name":"Can I edit the generated text before using it?","acceptedAnswer":{"@type":"Answer","text":"Yes — the output is text you copy and paste, not a locked file. Edit freely before adding it to your manuscript. The generator gives you a correct starting structure; you customize the wording to match your voice."}},{"@type":"Question","name":"I'm publishing under a pen name — does the tool handle that?","acceptedAnswer":{"@type":"Answer","text":"Yes. There's a separate pen name field. When filled in, the title page shows your pen name as the author while the copyright page can reflect your legal name underneath — standard practice for pen-name publishing."}},{"@type":"Question","name":"Do I need an ISBN to generate the copyright page?","acceptedAnswer":{"@type":"Answer","text":"No. The ISBN field is optional. If you leave it blank, the copyright page is generated without it. You can add the ISBN later manually once you have one, or leave it out entirely if you're publishing without an ISBN."}},{"@type":"Question","name":"What disclaimer type should I pick for my book?","acceptedAnswer":{"@type":"Answer","text":"Fiction covers the standard characters-are-fictional language. Health covers medical books that shouldn't be taken as professional advice. Finance covers investment or money books. General works for most non-fiction that doesn't fit the others. Leave it as None if your book doesn't need a disclaimer."}},{"@type":"Question","name":"Does the copyright page include standard legal language?","acceptedAnswer":{"@type":"Answer","text":"Yes. The copyright page includes the copyright notice, 'All rights reserved' language, your edition, publisher name, and ISBN if provided — all formatted to standard publishing conventions without you needing to know what goes where."}}]}</script>`,
        upsell: { text: 'Front matter done. Write back matter →', tool: 'back-matter-generator' },
        fields: [
            { id: 'title', label: 'Book title', type: 'text', placeholder: 'My Amazing Book' },
            { id: 'subtitle', label: 'Subtitle (optional)', type: 'text', placeholder: '' },
            { id: 'author', label: 'Author name', type: 'text', placeholder: 'Jane Doe' },
            { id: 'penName', label: 'Pen name (optional)', type: 'text', placeholder: 'Publishing under a different name?' },
            { id: 'year', label: 'Copyright year', type: 'text', placeholder: new Date().getFullYear().toString() },
            { id: 'publisher', label: 'Publisher name', type: 'text', placeholder: 'Self-Published' },
            { id: 'isbn', label: 'ISBN (optional)', type: 'text', placeholder: '' },
            {
                id: 'edition', label: 'Edition', type: 'select',
                options: ['First', 'Second', 'Third', 'Revised', 'Updated'],
            },
            { id: 'dedication', label: 'Dedication text (optional)', type: 'textarea', placeholder: 'To my family...' },
            {
                id: 'disclaimer', label: 'Disclaimer type', type: 'radio',
                options: [
                    { label: 'None', value: 'none' },
                    { label: 'Fiction', value: 'fiction' },
                    { label: 'Health', value: 'health' },
                    { label: 'Finance', value: 'finance' },
                    { label: 'General', value: 'general' },
                ],
            },
            {
                id: 'sections', label: 'Include sections', type: 'checkboxes', defaults: true,
                options: [
                    { id: 'titlePage', label: 'Title Page' },
                    { id: 'copyrightPage', label: 'Copyright Page' },
                    { id: 'dedicationPage', label: 'Dedication' },
                    { id: 'disclaimerPage', label: 'Disclaimer' },
                ],
            },
        ],
    },
    {
        slug: 'back-matter-generator',
        name: 'Back Matter Generator',
        seoTitle: 'Back Matter Generator — Author Bio, Also By & Closing Pages for KDP',
        h1: 'Back Matter Generator for Indie Authors',
        intro: 'AI-powered back matter generator for books. Writes your author bio, Also By section, reader list call-to-action, and closing note — professional back matter for KDP and EPUB in minutes.',
        category: 'structure',
        desc: 'AI writes your author bio, mailing list call-to-action, Also By section, and closing note. Professional back matter for indie authors done in minutes. No formatting experience needed.',
        type: 'ai',
        accessType: 'ai',
        creditCost: 2,
        free: false,
        seoContent: `<h2>Back Matter Generator for Books</h2><p>Most authors spend hours on back matter. Writing the acknowledgments, formatting the author bio, setting up the also-by page — it's tedious work that comes right at the end when you're already exhausted. This tool handles all of it.</p><h2>What Gets Generated</h2><p>Author bio written professionally in the tone you choose. Also By section listing your other titles cleanly. Reader list call-to-action to grow your mailing list. A note from the author for a personal touch. Acknowledgements section. Connect page with your social handles. Each section follows standard publishing conventions.</p><h2>Who This Is For</h2><p>Self-publishing authors who want professional back matter without hiring a formatter. Freelance editors who deliver complete manuscripts to clients. Anyone publishing more than one book a year who wants to stop rewriting the same sections from scratch.</p><h2>How to Use It</h2><p>Enter your author details, book title, and choose which sections you need. Select your tone and the tool generates everything instantly. Copy and paste directly into your manuscript.</p><script type="application/ld+json">{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"How many credits does this cost?","acceptedAnswer":{"@type":"Answer","text":"2 AI credits per generation."}},{"@type":"Question","name":"Can I edit what it generates, or is the output fixed?","acceptedAnswer":{"@type":"Answer","text":"The output is text you copy and paste — edit it freely before adding it to your manuscript. The generator produces a strong professional draft; you refine the details before using it."}},{"@type":"Question","name":"What if I don't have a mailing list yet?","acceptedAnswer":{"@type":"Answer","text":"Leave the mailing list URL field blank and uncheck the Join My Reader List section. The rest of the back matter generates normally. You can add the reader list section later by running the tool again once you have a signup link."}},{"@type":"Question","name":"How long is the author bio it writes?","acceptedAnswer":{"@type":"Answer","text":"It generates both a short bio (one paragraph, roughly 75–100 words) and a long bio (two to three paragraphs). The short version is for platform profiles and the back cover; the long version works for your About the Author page inside the book."}},{"@type":"Question","name":"Does it work for pen names?","acceptedAnswer":{"@type":"Answer","text":"Yes. Enter your pen name as the author name — the bio, connect page, and all sections are written using whatever name you provide. If you want the bio to acknowledge that it's a pen name, mention that in the author background field."}},{"@type":"Question","name":"What if I only want two or three sections, not all six?","acceptedAnswer":{"@type":"Answer","text":"Uncheck any sections you don't need before generating. Only the selected sections are produced. A common minimal set is Author Bio, Also By, and Join My Reader List — enough to give readers a next step without padding out the back matter."}},{"@type":"Question","name":"Will the Also By section work if I only have one other book, or even none yet?","acceptedAnswer":{"@type":"Answer","text":"Yes for one book — just enter the title. If you have no other books yet, skip that section entirely and add it on your next run once your second title is published. Don't include placeholder coming-soon entries; they signal a new author and undercut the professional tone the rest of the back matter sets."}}]}</script>`,
        upsell: { text: 'Back matter done. Format your full manuscript for Kindle →', tool: 'kindle-format-fixer' },
        fields: [
            { id: 'author', label: 'Author name', type: 'text', placeholder: 'Jane Doe' },
            { id: 'background', label: 'Author background (2-3 sentences)', type: 'textarea', placeholder: 'Tell us about yourself...' },
            { id: 'bookTitle', label: 'Book title', type: 'text', placeholder: 'My Book' },
            {
                id: 'genre', label: 'Genre', type: 'select',
                options: ['Romance', 'Thriller', 'Mystery', 'Fantasy', 'Sci-Fi', 'Literary Fiction', 'Self-Help', 'Business', 'Memoir', 'How-To', 'Health', 'Other'],
            },
            { id: 'otherBooks', label: 'Other books (one per line)', type: 'textarea', placeholder: 'Title - One-liner description' },
            { id: 'mailingListUrl', label: 'Mailing list URL', type: 'text', placeholder: 'https://...' },
            { id: 'readerMagnet', label: 'Reader magnet / offer (optional)', type: 'text', placeholder: 'Free short story for subscribers' },
            { id: 'socials', label: 'Social media handles (optional)', type: 'text', placeholder: '@handle on Twitter, Facebook, etc.' },
            {
                id: 'tone', label: 'Tone', type: 'radio',
                options: [
                    { label: 'Warm & personal', value: 'warm' },
                    { label: 'Professional', value: 'professional' },
                    { label: 'Slightly humorous', value: 'humorous' },
                ],
            },
            {
                id: 'sections', label: 'Sections to include', type: 'checkboxes', defaults: true,
                options: [
                    { id: 'authorBio', label: 'Author Bio (short + long)' },
                    { id: 'alsoBy', label: 'Also By This Author' },
                    { id: 'readerList', label: 'Join My Reader List' },
                    { id: 'connect', label: 'Connect With the Author' },
                    { id: 'noteFromAuthor', label: 'A Note From the Author' },
                    { id: 'acknowledgements', label: 'Acknowledgements' },
                ],
            },
        ],
        wordLimit: 500,
    },
    {
        slug: 'css-snippet-generator',
        name: 'CSS Snippet Generator',
        category: 'structure',
        desc: 'Get copy-paste CSS for drop caps, scene breaks, blockquotes, pull quotes, and more. Live preview included. Optimized for Kindle KFX and EPUB stylesheets. No coding experience needed.',
        type: 'logic',
        accessType: 'logic',
        creditCost: 0,
        free: false,
        seoContent: `<h2>CSS Snippet Generator for EPUB and Kindle</h2><p>Styling an EPUB file by hand means hunting for CSS that actually works across Kindle, Apple Books, and Kobo. Most generic CSS breaks on at least one platform. This tool generates tested snippets optimized for each.</p><h2>What It Generates</h2><p>Drop cap CSS for chapter openers. Scene break styles. Blockquote and pull quote formatting. First-line indent styles. No-indent after heading rules. Centered text. Poetry and verse formatting. Sidebar boxes. Letter and dialogue styles. Each snippet includes a live preview so you see exactly what it looks like before copying.</p><h2>Who This Is For</h2><p>Authors hand-coding their own EPUB files. Formatters who want reliable CSS without testing on every device. Anyone who has had drop caps break on Kindle after looking fine in Sigil.</p><h2>How to Use It</h2><p>Select the element you need, choose your platform target (Kindle, EPUB, or both), and copy the generated CSS directly into your stylesheet.</p><script type="application/ld+json">{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"Is this tool free to use?","acceptedAnswer":{"@type":"Answer","text":"It is a logic tool included in the Starter and Pro plans. No AI credits are used — generate as many snippets as you need."}},{"@type":"Question","name":"Do I need coding knowledge to use this?","acceptedAnswer":{"@type":"Answer","text":"No. Select the element you want, pick your platform target, and copy the generated CSS. The live preview shows exactly what it will look like before you copy anything. You don't need to understand CSS to use the output."}},{"@type":"Question","name":"Where does the CSS actually go in my file?","acceptedAnswer":{"@type":"Answer","text":"Paste it into your EPUB's stylesheet — typically style.css inside your EPUB package, linked from your XHTML chapter files. If you're working in Sigil, open the stylesheet file and paste the snippet at the bottom. For Kindle HTML files, paste it into the style block in your document's head section."}},{"@type":"Question","name":"Will it work on Apple Books and Kobo, not just Kindle?","acceptedAnswer":{"@type":"Answer","text":"Select Both (safe subset) and the generated CSS uses properties supported across Kindle KFX, Apple Books, and Kobo. The Kindle-only target uses some KFX-specific properties that don't translate to other readers. If you're publishing across multiple stores, always use the Both option."}},{"@type":"Question","name":"Can I customize the generated CSS, or is it locked?","acceptedAnswer":{"@type":"Answer","text":"It's plain text — edit it freely. The snippet is a correct, tested starting point. Adjust font sizes, colors, margins, or any other values to match your book's design."}},{"@type":"Question","name":"The preview looks right but it breaks on my actual device — what now?","acceptedAnswer":{"@type":"Answer","text":"Switch to the Both (safe subset) target if you haven't already — it uses the most universally supported CSS properties. Drop caps in particular can behave differently across Kindle firmware versions; the Kindle-specific drop cap snippet accounts for this, but some very old devices ignore it."}},{"@type":"Question","name":"I'm using Sigil or Calibre — how does this fit my workflow?","acceptedAnswer":{"@type":"Answer","text":"Generate the snippet here, then open your stylesheet in Sigil's book editor and paste it in. Calibre's edit-book mode works the same way. This tool saves you the time of writing and testing CSS by hand before you bring it into your editing environment."}}]}</script>`,
        upsell: { text: 'CSS ready. Validate your EPUB structure before uploading →', tool: 'epub-validator' },
        fields: [
            {
                id: 'element', label: 'Element', type: 'element-picker',
                options: [
                    { id: 'drop-cap', label: 'Drop Cap' },
                    { id: 'scene-break', label: 'Scene Break' },
                    { id: 'blockquote', label: 'Blockquote' },
                    { id: 'pull-quote', label: 'Pull Quote' },
                    { id: 'first-line-indent', label: 'First-Line Indent' },
                    { id: 'no-indent-after-heading', label: 'No-Indent After Heading' },
                    { id: 'centered-text', label: 'Centered Text' },
                    { id: 'poetry', label: 'Poetry/Verse' },
                    { id: 'sidebar-box', label: 'Sidebar Box' },
                    { id: 'letter-dialogue', label: 'Letter/Dialogue' },
                ],
            },
            {
                id: 'platform', label: 'Platform target', type: 'radio',
                options: [
                    { label: 'Kindle (KFX)', value: 'kindle' },
                    { label: 'EPUB Generic', value: 'epub' },
                    { label: 'Both (safe subset)', value: 'both' },
                ],
            },
        ],
    },

    // ── QUALITY CATEGORY ──────────────────────────────────────────────
    {
        slug: 'epub-validator',
        name: 'EPUB Validator',
        category: 'quality',
        desc: 'Free EPUB validator — no signup, no Java, no download. Check your .epub file for KDP, Apple Books, and IngramSpark errors before you upload.',
        seoTitle: 'Free EPUB Validator Online — No Java, No Upload, No Signup',
        h1: 'EPUB Validator — Free EPUB Checker for KDP',
        intro: 'Free EPUB validator and EPUB checker for indie authors. Upload your .epub file to catch the errors KDP, Apple Books, and IngramSpark flag before you submit — no Java, no signup, runs entirely in your browser.',
        accessType: 'free',
        creditCost: 0,
        free: true,
        related: [{ slug: 'kdp-keyword-finder', label: 'KDP Keyword Finder tool' }],
        upsell: null,
        seoContent: `<h2>Why EPUB Validation Matters Before You Upload to Any Store</h2><p>An EPUB file can open fine on your computer and still fail KDP upload. This isn't a bug — it's the gap between "can be opened" and "conforms to the EPUB specification." KDP, Apple Books, and IngramSpark each run automated validation when you submit. If your file fails, the rejection message is often vague. Running validation yourself first gives you the specific error, its location inside the file, and time to fix it before any store sees it.</p><h2>Your File Never Leaves Your Device</h2><p>Most online EPUB validators upload your file to a server, process it remotely, and return results. This validator is different: validation runs entirely in your browser using JavaScript. Your .epub file is read locally and never transmitted anywhere. No file upload, no server storage, no account needed, no privacy concern with manuscript content. Works on Windows, Mac, Linux, and Chromebook — anything with a modern browser.</p><h2>What EPUB Validation Checks</h2><p>An EPUB file is a zip archive containing several layers: the container declaration, a package document (.opf file), HTML content files, CSS, images, and navigation files. Validation checks every layer against the EPUB specification.</p><ul><li><strong>Mimetype</strong> — First file in the archive must be named "mimetype," contain exactly "application/epub+zip," and be stored uncompressed.</li><li><strong>Container (META-INF/container.xml)</strong> — Must exist and correctly point to the package document. Missing or malformed container.xml breaks every e-reader.</li><li><strong>OPF Package Document</strong> — Must list every content file in the manifest with correct media types. Unlisted files fail this check.</li><li><strong>Required Metadata</strong> — Title, language (dc:language), and unique identifier (dc:identifier) are mandatory. Missing any fails KDP upload.</li><li><strong>Spine</strong> — Reading order must reference valid manifest items. Broken spine means e-readers can't navigate linearly.</li><li><strong>Navigation (nav.xhtml / toc.ncx)</strong> — EPUB 3 needs nav.xhtml; EPUB 2 needs toc.ncx. Both must reference real content files.</li><li><strong>Cover Image</strong> — Must be correctly declared in manifest with properties="cover-image" (EPUB 3) or a meta name="cover" element (EPUB 2). KDP specifically checks cover linkage.</li><li><strong>Images and Fonts</strong> — Every file referenced in content HTML and CSS must exist in the manifest and the archive. Broken references cause display errors on devices.</li><li><strong>File Size</strong> — KDP has a maximum file size limit. Large image-heavy EPUBs fail at upload if exceeded.</li></ul><h2>Common EPUB Validation Errors — Specific Fixes</h2><p><strong>Missing manifest resource (what EPUBCheck calls PKG-026):</strong> A file is referenced in the OPF manifest but doesn't exist inside the archive, or exists in the archive but isn't declared in the manifest. Fix: open your .opf file and add the missing item with the correct media type, or remove the declaration if the file was deleted.</p><p><strong>Missing dc:language or dc:identifier:</strong> Required OPF metadata is absent. Fix: add dc:language (BCP 47 tag like "en" or "en-US") and dc:identifier (any unique string, typically your ISBN or a UUID) to the metadata section of your .opf file.</p><p><strong>Navigation structure error:</strong> nav.xhtml is missing, malformed, or references files that don't exist. Fix: ensure nav.xhtml has a valid epub:type="toc" nav element with li entries pointing to real file locations with correct relative paths.</p><p><strong>Broken image or font reference:</strong> An img tag or CSS @font-face references a file path that doesn't exist inside the archive. Paths are case-sensitive on some platforms. Fix: verify the exact path, confirm the file exists in the archive with that exact capitalization, and ensure it's listed in the manifest.</p><p><strong>Cover reference error:</strong> EPUB 3 needs manifest item with properties="cover-image"; EPUB 2 needs meta name="cover" pointing to the cover image manifest ID. Missing either causes KDP's cover check to fail even if the image is physically present.</p><p><strong>EMF/WMF image error:</strong> Images in Windows-only EMF or WMF format fail validation. Fix: open your original Word file, re-save those images as PNG or JPG, replace them, and re-export to EPUB.</p><h2>EPUB Validation: KDP vs. Apple Books vs. IngramSpark</h2><p><strong>Amazon KDP</strong> is the most lenient. It accepts EPUB 2 and EPUB 3, tolerates some malformed XML, and sometimes auto-corrects minor issues rather than rejecting the file. Its error messages are often generic ("We found issues with your file") — making self-validation even more important, since KDP won't always tell you specifically what went wrong.</p><p><strong>Apple Books</strong> is the strictest. It requires EPUB 3, rejects files with invalid XML, and performs additional checks on image quality and font embedding. Getting a rejection from Apple Books after successfully uploading to KDP is common. Validate before Apple Books submission — issues that KDP ignores will cause Apple Books rejections.</p><p><strong>IngramSpark</strong> sits between the two. It accepts EPUB 3 with standard compliance requirements and provides clearer rejection messages than KDP.</p><h2>EPUB 3 vs. EPUB 2 — Which Do You Need?</h2><p>EPUB 3 is the current standard and required by Apple Books. KDP and most other stores accept both. If you're distributing to multiple stores, use EPUB 3 — it satisfies every store's requirements. EPUB 2 files are still accepted by KDP but may cause issues with Apple Books submission. The validator detects which version your file declares and applies version-appropriate checks.</p><h2>Free Scan vs. Pro Scan</h2><p>The free validator runs 11 structural checks automatically — mimetype, container, OPF, required metadata, spine, manifest, EMF images, font files, navigation, cover image, and file size — in a single pass when you drop your file. This catches the structural errors that cause outright upload rejection at any store.</p><p>The Pro Scan adds deeper content-level validation: ghost spacing detection, duplicate ID scanning, OPF manifest cross-check, cover dimension verification, and a store-specific pass/fail report for KDP, Apple Books, and Google Play. It runs as a separate check using 2 credits from your BookKraft account.</p><h2>Free EPUB Validator — No EPUBCheck Installation Needed</h2><p>EPUBCheck — the official reference validator — requires Java and command-line access. Most authors don't have Java installed and shouldn't need to install it just to check a file. This validator runs equivalent structural checks entirely in the browser. Drop the file, get results in seconds. No Java, no terminal, no uploading your manuscript to a third-party server.</p><script type="application/ld+json">{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"Is the EPUB Validator free?","acceptedAnswer":{"@type":"Answer","text":"Yes, completely free. No account, no signup, no credit card, no usage limit. Run it as many times as needed."}},{"@type":"Question","name":"Is my EPUB file uploaded to your server?","acceptedAnswer":{"@type":"Answer","text":"No. Validation runs entirely in your browser using JavaScript. Your file is read locally and never transmitted anywhere — no upload, no server storage, no privacy concern with manuscript content."}},{"@type":"Question","name":"Do I need Java or desktop software?","acceptedAnswer":{"@type":"Answer","text":"No. This validator runs in any modern browser — no Java, no Calibre, no Sigil, nothing to install. Works on Windows, Mac, Linux, and Chromebook."}},{"@type":"Question","name":"What checks does the free validator run?","acceptedAnswer":{"@type":"Answer","text":"The free validator runs 11 checks automatically: mimetype format, container.xml structure, OPF package document, required metadata (title, language, identifier), spine reading order, navigation document, cover image declaration, EMF/WMF image detection, font file references, manifest completeness, and file size. All checks run in one pass when you drop your file."}},{"@type":"Question","name":"What is the difference between the free scan and Pro Scan?","acceptedAnswer":{"@type":"Answer","text":"The free scan runs 11 structural checks automatically. The Pro Scan adds ghost spacing detection, duplicate ID scanning, OPF manifest cross-check, cover dimension verification, and a store-specific pass/fail report for KDP, Apple Books, and Google Play. Pro Scan costs 2 credits from a BookKraft account."}},{"@type":"Question","name":"My file uploaded to KDP fine — do I still need to validate?","acceptedAnswer":{"@type":"Answer","text":"KDP accepts some technically invalid files by auto-correcting them internally. A file that uploads to KDP might still fail Apple Books, IngramSpark, or Kobo, which are stricter. Validating catches these issues before they become rejections."}},{"@type":"Question","name":"What is EPUBCheck PKG-026?","acceptedAnswer":{"@type":"Answer","text":"PKG-026 is an EPUBCheck error code meaning a file is referenced in the OPF manifest but doesn't exist inside the archive, or it exists in the archive but isn't declared in the manifest. This validator surfaces the same issue under the Manifest Files check — it shows how many files are missing and links to the fix guide."}},{"@type":"Question","name":"Does this validate EPUB 2 and EPUB 3?","acceptedAnswer":{"@type":"Answer","text":"Yes, both are accepted. EPUB 3 is the current standard and required by Apple Books; EPUB 2 is still accepted by KDP. The validator detects which version your file declares and applies version-appropriate checks."}},{"@type":"Question","name":"Is this the same as EPUBCheck?","acceptedAnswer":{"@type":"Answer","text":"EPUBCheck is the official EPUB validation tool maintained by the EPUB standards body. It requires Java and command-line access. This tool runs equivalent structural validation checks in a browser with no installation required. The results are comparable for the structural errors that cause store rejections."}}]}</script>`,
        fields: [
            { id: 'file', label: 'Drop your .epub file here or click to browse', type: 'file', accept: '.epub' },
            {
                id: 'level', label: 'Validation level', type: 'radio',
                options: [
                    { label: 'Quick Check (structure)', value: 'quick' },
                    { label: 'Full Check (structure + content)', value: 'full' },
                ],
            },
        ],
    },
    {
        slug: 'epub-validator-premium',
        name: 'EPUB Validator Pro',
        category: 'quality',
        desc: 'Deep EPUB validation — ghost spacing detection, duplicate ID scan, OPF manifest check, cover dimensions, and store-specific pass/fail report for KDP, Apple Books, and Google Play.',
        type: 'ai',
        accessType: 'ai',
        creditCost: 2,
        free: false,
        seoContent: `<h2>EPUB Validator Pro for KDP and Apple Books</h2><p>The free EPUB validator catches basic structure errors. This tool goes deeper — ghost spacing, duplicate IDs, OPF manifest issues, and cover dimension problems that cause rejections on KDP, Apple Books, and Google Play.</p><h2>What It Checks</h2><p>Ghost spacing that breaks reflowable text. Duplicate ID errors that cause navigation failures. OPF manifest completeness. Cover image dimensions against store requirements. Store-specific pass/fail report for KDP, Apple Books, and Google Play so you know exactly where your file will be accepted.</p><h2>Who This Is For</h2><p>Authors who have had an EPUB rejected by a store without a clear reason. Formatters delivering files to clients who publish across multiple platforms. Anyone uploading to Apple Books or Google Play where validation requirements are stricter than KDP.</p><h2>How to Use It</h2><p>Upload your EPUB file and get a detailed report with pass/fail status for each store and specific fixes for every issue found.</p><script type="application/ld+json">{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"How is this different from the free EPUB Validator?","acceptedAnswer":{"@type":"Answer","text":"The free validator checks structural integrity — mimetype, container, OPF, metadata, spine, navigation, cover reference, and file size. The Pro scan goes deeper: ghost spacing, duplicate ID errors, OPF manifest completeness, cover image dimensions against store requirements, and a store-by-store pass/fail breakdown for KDP, Apple Books, and Google Play."}},{"@type":"Question","name":"How many credits does this cost?","acceptedAnswer":{"@type":"Answer","text":"2 AI credits per validation."}},{"@type":"Question","name":"My file passed the free validator — do I still need the Pro scan?","acceptedAnswer":{"@type":"Answer","text":"Possibly. The free validator confirms your file is structurally readable. It won't catch ghost spacing, duplicate IDs, or a cover image that's the wrong dimensions for a specific store. If you're submitting to Apple Books, Google Play, or IngramSpark — all stricter than KDP — the Pro scan is worth running before uploading."}},{"@type":"Question","name":"What exactly is ghost spacing and why does it matter?","acceptedAnswer":{"@type":"Answer","text":"Ghost spacing is leftover empty paragraph tags or non-breaking space characters carried over from a Word or Google Docs export. They're invisible in most previews but cause inconsistent gaps between paragraphs on actual eReaders. Apple Books flags these during review; KDP is more forgiving but the reading experience suffers."}},{"@type":"Question","name":"What does the store-specific report tell me?","acceptedAnswer":{"@type":"Answer","text":"It gives a separate pass/fail result for KDP, Apple Books, and Google Play, showing which issues would cause a rejection on each store specifically. The same file can pass KDP and fail Apple Books — the report tells you exactly where and why."}},{"@type":"Question","name":"Can it fix the issues it finds, or does it only report them?","acceptedAnswer":{"@type":"Answer","text":"It reports issues with specific locations and descriptions so you know exactly what to fix and where. Fixing deep structural issues like duplicate IDs or ghost spacing requires editing the underlying EPUB source files — use the report to guide those edits in Sigil or your EPUB editor."}},{"@type":"Question","name":"Should I run the free validator first, or go straight to Pro?","acceptedAnswer":{"@type":"Answer","text":"Run the free validator first. If it finds structural errors, fix those before running the Pro scan — the Pro scan's deeper checks are only meaningful once the basic structure is sound."}}]}</script>`,
        upsell: { text: 'Validation complete. Fix your EPUB structure →', tool: 'epub-formatter' },
        fields: [
            { id: 'file', label: 'Drop your .epub file here or click to browse', type: 'file', accept: '.epub' },
        ],
    },
    {
        slug: 'style-sheet-auditor',
        name: 'Style Sheet Auditor',
        seoTitle: 'Style Sheet Auditor for Manuscripts — AI Consistency Checker',
        h1: 'Style Sheet Auditor for Manuscripts',
        intro: 'AI scans your full manuscript for style inconsistencies — character name variations, capitalisation drift, hyphenation, and dialogue punctuation changes — that spell checkers miss. Free sample run available.',
        category: 'quality',
        desc: 'AI scans your manuscript for style inconsistencies — character names, capitalisation, hyphenation, dialogue punctuation — that human editors charge hundreds to catch. Any manuscript length, full novels included.',
        type: 'ai',
        accessType: 'ai',
        creditCost: 1,
        free: false,
        hasSample: true,
        seoContent: `<h2>Style Sheet Auditor for Manuscripts</h2><p>Human editors charge hundreds of dollars to catch style inconsistencies across a full manuscript. This tool scans your text and finds them in seconds — character name variations, capitalization changes, hyphenation inconsistencies, and dialogue punctuation style drift.</p><h2>What It Catches</h2><p>Character names spelled differently across chapters. Capitalization rules applied inconsistently. Hyphenation used in some places but not others for the same word. Dialogue punctuation style changing mid-manuscript. Number formatting inconsistencies. POV drift within scenes.</p><h2>Who This Is For</h2><p>Authors self-editing before sending to a professional editor. Editors building a style sheet for a new client manuscript. Anyone who has been told by a reader that character names seemed to change.</p><h2>How to Use It</h2><p>Paste any length manuscript, add your existing style sheet rules if you have them, select which categories to check, confirm the cost, and get a detailed inconsistency report with locations and suggested fixes. Longer manuscripts are split by chapter and audited in the background with live progress.</p><script type="application/ld+json">{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"Is there a free sample before I spend credits?","acceptedAnswer":{"@type":"Answer","text":"Yes. A free 500-word sample run is available so you can see the output format and check quality before committing credits. Run it on a representative chapter section — somewhere with dialogue and character names — to get a meaningful preview."}},{"@type":"Question","name":"Will it rewrite my manuscript, or only flag issues?","acceptedAnswer":{"@type":"Answer","text":"It only flags and reports. You receive a list of inconsistencies with their locations and suggested fixes — nothing in your manuscript is changed automatically. Every decision about what to fix stays with you."}},{"@type":"Question","name":"How does it show me where the inconsistencies are?","acceptedAnswer":{"@type":"Answer","text":"The report includes the specific text, the chapter or section it appears in, and what the inconsistency is. You can search your manuscript for the flagged text and make targeted fixes rather than re-reading the full document."}},{"@type":"Question","name":"What if I'm intentionally repeating a word or phrase for stylistic effect?","acceptedAnswer":{"@type":"Answer","text":"The tool flags repetition based on proximity and frequency. Deliberate stylistic repetition may be flagged. Review the report critically — accept the flag where it's a real error, ignore it where it's intentional. The output is a list of candidates, not a list of mandated changes."}},{"@type":"Question","name":"I don't have a style sheet yet — does that mean I can't use this?","acceptedAnswer":{"@type":"Answer","text":"Leave the style sheet field blank and the tool auto-detects your manuscript's implicit conventions. The spelling and capitalization pattern used most often is treated as the intended standard. Creating a style sheet isn't a prerequisite; the tool helps you build one from what it finds."}},{"@type":"Question","name":"How many credits does a full novel cost?","acceptedAnswer":{"@type":"Answer","text":"Cost scales with word count and is shown before you confirm the run. A 500-word free sample is available first so you can judge output quality before spending any credits."}},{"@type":"Question","name":"I'm writing a series — can I use it to keep character names consistent across books?","acceptedAnswer":{"@type":"Answer","text":"Yes, and this is one of its strongest use cases for series authors. Paste each volume individually and include your series style sheet — character names, place names, established capitalization rules — in the style sheet field. The tool checks the current manuscript against those rules, catching drift from the series standard before your readers notice it."}}]}</script>`,
        upsell: { text: 'Style audit complete. Ready to format for Kindle? →', tool: 'kindle-format-fixer' },
        fields: [
            { id: 'text', label: 'Paste your manuscript (any length)', type: 'textarea', placeholder: 'Paste your text...' },
            { id: 'styleSheet', label: 'Known style rules (optional)', type: 'textarea', placeholder: 'Paste your existing style sheet, or leave blank for auto-detection...' },
            {
                id: 'categories', label: 'Check these categories', type: 'checkboxes', defaults: true,
                options: [
                    { id: 'charNames', label: 'Character name consistency' },
                    { id: 'capitalisation', label: 'Capitalisation rules' },
                    { id: 'hyphenation', label: 'Hyphenation consistency' },
                    { id: 'dialoguePunct', label: 'Dialogue punctuation style' },
                    { id: 'numberFormat', label: 'Number formatting (digits vs words)' },
                    { id: 'povConsistency', label: 'POV consistency' },
                ],
            },
        ],
    },
    {
        slug: 'word-cleanup',
        name: 'Word Manuscript Cleanup Checker',
        category: 'quality',
        desc: 'Free Word manuscript scanner. Upload your .docx and instantly check for double spaces, straight quotes, stacked blank paragraphs, and stray bold/italic formatting before you publish. No signup needed.',
        accessType: 'free',
        creditCost: 0,
        free: true,
        standalone: true, // own route at /tools/word-cleanup, not rendered via ToolPageClient
        related: [{ slug: 'epub-validator', label: 'EPUB Validator tool' }],
        upsell: { text: 'Manuscript scanned. Now clean it up with AI →', tool: 'manuscript-cleanup' },
    },
    {
        slug: 'cover-checker',
        name: 'Cover Checker',
        category: 'quality',
        desc: 'Free KDP and Apple Books cover dimension checker. Upload your cover and instantly check pixel, ratio, and format requirements before you upload it anywhere. No signup needed.',
        accessType: 'free',
        creditCost: 0,
        free: true,
        standalone: true, // own route at /tools/cover-checker, not rendered via ToolPageClient
        related: [{ slug: 'epub-validator', label: 'EPUB Validator tool' }],
    },
    {
        slug: 'manuscript-mode',
        name: 'Full Manuscript Mode',
        category: 'formatting',
        desc: 'Free one-step DOCX or TXT to EPUB 3.0 converter. Detects chapters, fixes smart quotes, em dashes, and encoding artifacts, and generates a valid EPUB — no Calibre, no Sigil, no signup.',
        accessType: 'free',
        creditCost: 0,
        free: true,
        standalone: true, // own route at /tools/manuscript-mode, not rendered via ToolPageClient
        upsell: { text: 'EPUB generated. Validate it before you upload →', tool: 'epub-validator' },
    },

    // ── PUBLISHING CATEGORY ──────────────────────────────────────────────
    {
        slug: 'metadata-builder',
        name: 'Metadata Builder',
        category: 'publishing',
        desc: 'Build complete book metadata formatted for KDP, IngramSpark, Draft2Digital, and EPUB OPF files. Includes keywords, BISAC categories, and pricing fields. Free tool for indie authors. No account required.',
        seoTitle: 'Metadata Builder for KDP — Free Book Metadata Generator',
        h1: 'Metadata Builder for KDP, IngramSpark & EPUB',
        intro: 'Metadata Builder for KDP creates complete book metadata for KDP, IngramSpark, Draft2Digital, and EPUB OPF files in one step — title, subtitle, BISAC categories, keywords, and pricing formatted correctly for each platform. Free, no account required.',
        type: 'logic',
        accessType: 'free',
        creditCost: 0,
        free: true,
        related: [{ slug: 'kdp-keyword-finder', label: 'KDP Keyword Finder tool' }],
        upsell: { text: 'Metadata ready. Find the best KDP keywords →', tool: 'kdp-keyword-finder' },
        seoContent: `<h2>Metadata Builder for KDP and IngramSpark</h2><p>Book metadata is scattered across different formats depending on where you publish. KDP wants one format, IngramSpark another, EPUB OPF files yet another. This tool builds all of it at once from a single form.</p><h2>What It Generates</h2><p>Complete metadata for KDP, IngramSpark, Draft2Digital, and EPUB OPF files. Includes title, subtitle, series info, BISAC categories, keywords, short and long descriptions, ISBN/ASIN, publication date, edition, language, and pricing in USD, GBP, EUR, and AUD.</p><h2>Who This Is For</h2><p>Authors publishing the same book across multiple platforms who don't want to re-enter metadata each time. First-time authors unsure what BISAC categories or keywords to use. Anyone preparing a new release for KDP and IngramSpark at the same time.</p><h2>How to Use It</h2><p>Fill in your book details, categories, keywords, and pricing once. The tool formats everything correctly for each platform, ready to copy and paste.</p><script type="application/ld+json">{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"Is the Metadata Builder free?","acceptedAnswer":{"@type":"Answer","text":"Yes. Completely free — no account, no signup, no credits required."}},{"@type":"Question","name":"How do I find the right BISAC category for my book?","acceptedAnswer":{"@type":"Answer","text":"BISAC categories follow a hierarchical structure. Start with your primary genre and drill down to the most specific subcategory that fits. Check where comparable titles on Amazon or IngramSpark are categorized and use those as a guide. KDP also lets you browse its category list from the dashboard."}},{"@type":"Question","name":"What's the difference between the short and long description fields?","acceptedAnswer":{"@type":"Answer","text":"The short description (150 words max) is used for platform summary fields and back cover copy. The long description (400 words / 4,000 characters for KDP) is your full sales page copy — this is what appears on your Amazon product page and has the most impact on conversion."}},{"@type":"Question","name":"Do I need an ISBN before I can use this?","acceptedAnswer":{"@type":"Answer","text":"No. ISBN and ASIN fields are optional. Fill in what you have and leave the rest blank — you can always add the ISBN manually once you have one and update your platform listings."}},{"@type":"Question","name":"My book isn't listed anywhere yet — can I use this to prepare metadata in advance?","acceptedAnswer":{"@type":"Answer","text":"Yes — that's the ideal time to use it. Build your complete metadata before launch, export it for each platform, and have it ready to paste when you create your listings. Getting metadata right before the first upload is significantly easier than updating it after the fact across multiple platforms."}},{"@type":"Question","name":"Can I save my metadata and come back to it later?","acceptedAnswer":{"@type":"Answer","text":"The tool generates output you copy and paste — it doesn't store your data between sessions. Save your filled-in metadata to a document so you can update it and re-run the tool for future editions without re-entering everything from scratch."}},{"@type":"Question","name":"Does it format keywords differently for each platform?","acceptedAnswer":{"@type":"Answer","text":"Yes. KDP expects seven keyword phrases entered as separate fields. IngramSpark uses a comma-separated string. EPUB OPF uses a dc:subject tag for each keyword. The tool outputs each platform's format correctly so you're not manually reformatting the same keywords four different ways."}}]}</script>`,
        fields: [
            { id: 'title', label: 'Book title', type: 'text', placeholder: 'My Book' },
            { id: 'subtitle', label: 'Subtitle (optional)', type: 'text', placeholder: '' },
            { id: 'authors', label: 'Author name(s)', type: 'text', placeholder: 'Jane Doe' },
            { id: 'series', label: 'Series name (optional)', type: 'text', placeholder: '' },
            { id: 'seriesVolume', label: 'Volume number (optional)', type: 'text', placeholder: '' },
            { id: 'bisacCategory1', label: 'BISAC Category 1', type: 'text', placeholder: 'Search categories...' },
            { id: 'bisacCategory2', label: 'BISAC Category 2 (optional)', type: 'text', placeholder: 'Search categories...' },
            { id: 'kw1', label: 'Keyword 1', type: 'text', placeholder: '' },
            { id: 'kw2', label: 'Keyword 2', type: 'text', placeholder: '' },
            { id: 'kw3', label: 'Keyword 3', type: 'text', placeholder: '' },
            { id: 'kw4', label: 'Keyword 4', type: 'text', placeholder: '' },
            { id: 'kw5', label: 'Keyword 5', type: 'text', placeholder: '' },
            { id: 'kw6', label: 'Keyword 6', type: 'text', placeholder: '' },
            { id: 'kw7', label: 'Keyword 7', type: 'text', placeholder: '' },
            { id: 'shortDesc', label: 'Short description (150 words max)', type: 'textarea', placeholder: '' },
            { id: 'longDesc', label: 'Long description (400 words max / 4000 chars for KDP)', type: 'textarea', placeholder: '' },
            { id: 'isbn', label: 'ISBN (optional)', type: 'text', placeholder: '' },
            { id: 'asin', label: 'ASIN (optional)', type: 'text', placeholder: '' },
            { id: 'pubDate', label: 'Publication date', type: 'text', placeholder: 'YYYY-MM-DD' },
            {
                id: 'edition', label: 'Edition', type: 'select',
                options: ['First', 'Second', 'Third', 'Revised', 'Updated'],
            },
            {
                id: 'language', label: 'Language', type: 'select',
                options: ['English', 'Spanish', 'French', 'German', 'Portuguese', 'Italian', 'Dutch'],
            },
            { id: 'priceUSD', label: 'Price (USD)', type: 'text', placeholder: '9.99' },
            { id: 'priceGBP', label: 'Price (GBP)', type: 'text', placeholder: '' },
            { id: 'priceEUR', label: 'Price (EUR)', type: 'text', placeholder: '' },
            { id: 'priceAUD', label: 'Price (AUD)', type: 'text', placeholder: '' },
        ],
    },
    {
        slug: 'kdp-keyword-finder',
        name: 'KDP Keyword & Category Finder',
        category: 'publishing',
        desc: 'Find high-ranking KDP keywords and Amazon category paths for your book with AI. Boost discoverability and reach more readers in seconds.',
        seoTitle: 'Free KDP Keyword Finder — No Signup, Publisher Rocket Alternative',
        h1: 'KDP Keyword Finder — Amazon Keywords & Category Paths',
        intro: "Our KDP Keyword & Category Finder generates long-tail Amazon search terms and KDP category keywords your book needs to get found. Use it as a KDP category finder to surface ghost categories and narrow subcategories where competition is lower and bestseller rank is within reach.",
        seoContent: `<h2>Why Amazon KDP Keywords Determine Whether Your Book Gets Found</h2><p>Amazon's search algorithm — sometimes called A9 or A10 — matches reader queries to book listings using keywords, category placement, and sales velocity. The keywords you enter when publishing directly affect which searches surface your book. Get them wrong and Amazon has no signal to connect your book to readers who want it.</p><p>Most authors treat keyword entry as an afterthought — pick a few obvious terms, move on, wonder why organic traffic never comes. Authors who get consistent discovery treat keyword research the same way they treat cover design: something to get right before launch, not something to fix afterward.</p><h2>How Amazon's Search Algorithm Uses Your 7 Keyword Slots</h2><p>KDP gives you 7 keyword fields, each up to 50 characters. Amazon uses them to determine which search results your book appears in, which "Customers also bought" chains it enters, and which ad targeting groups it's eligible for.</p><ul><li><strong>Phrases outperform single words.</strong> "cozy mystery with recipes" is a phrase real readers type. "mystery" alone puts you against every mystery on Amazon. Use all 50 characters as a phrase, not comma-separated single words.</li><li><strong>Your title words don't need repeating.</strong> Amazon already indexes your title and subtitle. Adding "lighthouse" to a keyword slot when your title is <em>The Lighthouse Keeper's Secret</em> wastes a slot. Use keywords for angles your title doesn't cover.</li><li><strong>Amazon bans certain terms.</strong> No superlatives ("best," "top"), no price references ("on sale," "cheap"), no category names as keywords, no competitor author or brand names. Violations get keywords stripped or the listing flagged.</li></ul><h2>The Alphabet Method — How to Research KDP Keywords Manually</h2><p>Before using any tool, the most reliable signal is Amazon's own search autocomplete. Go to Amazon's book search. Type your genre followed by a space and the letter "a" — watch the autocomplete suggestions. Then repeat with "b," "c," and so on through the alphabet. Every suggestion is a real phrase that real readers typed in high enough volume for Amazon to surface it.</p><p>For a cozy mystery: "cozy mystery a" → "cozy mystery animals," "cozy mystery at a bakery," "cozy mystery anthology." Each is a potential keyword phrase, already validated by Amazon as something buyers search. This takes 20–30 minutes to do thoroughly. This tool does it automatically across your specific genre, themes, and target reader profile — and filters out prohibited terms before you see the results.</p><h2>KDP Categories — Ghost Categories and the 10-Category Limit</h2><p>KDP lets you select 2 categories during upload. You can request up to 10 by emailing KDP support after publishing. Most authors never do this, leaving 8 category slots empty.</p><p><strong>Ghost categories</strong> exist in Amazon's browse tree — you can find books listed in them — but they don't appear in the KDP publisher interface. The only way in is emailing KDP support with your ASIN and the exact category path. Ghost categories often have far less competition and more attainable bestseller ranks because most authors don't know they exist.</p><p>This tool outputs the full category path text you paste into a KDP support request, including ghost categories matched to your book's genre and themes.</p><h2>Fiction vs. Nonfiction KDP Keywords — Different Rules</h2><p>Fiction readers search by trope, setting, and sub-genre: "enemies to lovers slow burn," "historical romance Victorian England," "dark fantasy magic academy," "thriller psychological unreliable narrator." They search for what the reading experience feels like, not what the book is about in a literary sense.</p><p>Nonfiction readers search by problem, outcome, and audience: "how to start a business with no money," "meal prep weight loss beginners," "stoic philosophy daily practice," "divorce financial survival guide." They search for what they want to achieve.</p><p>Mixing the two patterns is the most common mistake — a nonfiction author targeting fiction-reader phrase structures, or a fantasy author using topic-based phrases no fantasy reader would type.</p><h2>Free KDP Keyword Tool — No Signup Required, Publisher Rocket Alternative</h2><p>Publisher Rocket ($97 one-time) is the most widely-used paid KDP keyword tool. It pulls real Amazon search volume data and historical BSR trends — if you publish frequently and want hard search-volume numbers backed by live API data, it's worth the investment. This tool works differently: it doesn't have access to Amazon's search volume API or historical sales data. What it does is generate AI-crafted keyword phrases tailored to your specific book — formatted as complete phrases within KDP's 50-character limit, filtered against Amazon's prohibited terms list, with ghost category paths included — free and without requiring an account to try. Different use case, different tradeoff.</p><h2>What This Tool Does</h2><p>Enter your book title, genre, comparable titles, target reader, and key themes. The tool generates 7 keyword phrases formatted for KDP's backend keyword fields — complete phrases within the 50-character limit, each with a character count shown. It also recommends primary and alternative category paths including specific ghost categories, with the exact path text needed for a KDP support request and a rationale for each recommendation.</p><h2>Who This Is For</h2><p>First-time authors who want keywords right before launch, not scrambling to fix them after. Experienced authors whose listings have low organic traffic and need re-optimization. Series authors wanting keywords that connect new installments to existing series momentum. Editors and publishing consultants handling KDP setup for clients.</p><script type="application/ld+json">{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"How many keyword slots does Amazon KDP give you?","acceptedAnswer":{"@type":"Answer","text":"Amazon KDP gives you 7 keyword fields, each up to 50 characters including spaces. Use each slot as a complete keyword phrase — not a list of single words — to match the specific search queries real readers type."}},{"@type":"Question","name":"What is a ghost category on Amazon KDP?","acceptedAnswer":{"@type":"Answer","text":"A ghost category is a real Amazon browse category that doesn't appear in the standard KDP category picker during upload. These categories exist in Amazon's public browse tree but are only accessible by emailing KDP support with your ASIN and the exact category path. Ghost categories often have less competition because most authors don't know they exist."}},{"@type":"Question","name":"Can I add more than 2 categories to my KDP book?","acceptedAnswer":{"@type":"Answer","text":"Yes. You select 2 categories during upload but can request up to 10 total by contacting KDP support after publishing. Email them your book's ASIN and the full category paths you want added — including ghost categories not available in the standard picker."}},{"@type":"Question","name":"What keywords are banned on Amazon KDP?","acceptedAnswer":{"@type":"Answer","text":"Amazon prohibits superlatives (best, top, greatest), price or promotional references (sale, cheap, discount), words already in your title, category names used as keywords, and competitor brand or author names. Violations can get keywords stripped or your listing flagged."}},{"@type":"Question","name":"Is this a free Publisher Rocket alternative?","acceptedAnswer":{"@type":"Answer","text":"They do different things. Publisher Rocket pulls real Amazon search volume data and historical BSR trends — useful if you want hard numbers and publish frequently. This tool generates AI-crafted keyword phrases tailored to your specific book, formatted for KDP's 50-character fields and filtered against Amazon's prohibited terms list, with ghost category paths included. It doesn't have access to Amazon's search volume API, so there are no volume numbers. Free to try without an account."}},{"@type":"Question","name":"Should I use keyword phrases or single words in KDP keyword slots?","acceptedAnswer":{"@type":"Answer","text":"Always use complete phrases. Single words like 'romance' or 'thriller' compete against every book in the genre. Phrases like 'small town romance with pets' or 'psychological thriller unreliable narrator' match specific queries real readers type and face far less competition."}},{"@type":"Question","name":"How often should I update my KDP keywords?","acceptedAnswer":{"@type":"Answer","text":"Review and update every 60–90 days, or sooner if organic traffic drops significantly. Seasonal trends, new competing titles, and algorithm changes all affect keyword performance. Run fresh research before updating to avoid replacing working keywords with untested ones."}},{"@type":"Question","name":"Do KDP keywords affect which categories my book appears in?","acceptedAnswer":{"@type":"Answer","text":"Yes. Amazon uses your keyword slots along with your selected categories to determine browse placement. Some categories are only accessible through specific keywords. Using category-relevant phrases in your backend keywords can improve browse placement beyond the categories you formally selected."}}]}</script>`,
        type: 'ai',
        accessType: 'ai',
        creditCost: 1,
        free: false,
        upsell: null,
        fields: [
            { id: 'title', label: 'Book title', type: 'text', placeholder: 'My Book' },
            {
                id: 'genre', label: 'Genre', type: 'select',
                options: [
                    'Cozy Mystery', 'Thriller', 'Romance', 'Fantasy', 'Sci-Fi', 'Literary Fiction',
                    'Horror', 'Historical Fiction', 'Self-Help', 'Business', 'Memoir', 'How-To',
                    'Health & Wellness', 'Finance', 'Parenting', 'Travel', 'Cooking', 'Other',
                ],
            },
            { id: 'reader', label: 'Target reader (2-3 sentences)', type: 'textarea', placeholder: 'Who reads this book?' },
            { id: 'comps', label: 'Comparable titles/authors', type: 'text', placeholder: 'Top 3 similar books or authors' },
            { id: 'themes', label: 'Key themes/topics', type: 'textarea', placeholder: 'Tropes, settings, topics, outcomes...' },
        ],
        wordLimit: 500,
    },
];

// Helper: find tool by slug
export function getToolBySlug(slug) {
    return TOOLS.find((t) => t.slug === slug) || null;
}

// Helper: get tools by category
export function getToolsByCategory(category) {
    if (category === 'all') return TOOLS;
    return TOOLS.filter((t) => t.category === category);
}